### ISSUE TITLE
v7 Installer is no longer gracefully failing in CI context

### ISSUE THREAD

**Issue by cmdcarini** [typicode/husky#1000]
**Context**
When running builds w/ Husky v7 in the CI, it seems that the Husky install is no longer failing gracefully, and is skipping over the `git rev-parse` [command](https://github.com/typicode/husky/blob/d47ffe1b6d80eaab3e1706d8a22562c737beb888/src/index.ts#L14) that usually halts the install process right away. 

Instead the install is now failing on [line 27 of the installer](https://github.com/typicode/husky/blob/d47ffe1b6d80eaab3e1706d8a22562c737beb888/src/index.ts#L27), that it can't find a .git directory.

**Comment by typicode** [comment]
That would be a regression

**Comment by typicode** [comment]
I did some tests.

It "works" like before except that the message is the one from git instead of a custom one.
But both in v6 or v7, the exit code is 0.

Instead of showing a custom "husky - not a Git repository, skipping hooks installation", I'm thinking that maybe showing Git error message is better. As you can find more info on the web with "fatal: not a git repository ..." rather than the husky one.

**Comment by typicode** [comment]
That said, in CI context you can disable `prepare` script if you want:
https://typicode.github.io/husky/#/?id=disable-husky-in-cidocker

**Comment by cmdcarini** [comment]
Hmm, ok. I'll have to take another look and see what's actually wrong with our use. The Docker use-case seems to be exactly what I'm looking for, I'll give that a shot. 

Thanks for the feedback and review!

**Comment by typicode** [comment]
Thanks for the PR :)
