### ISSUE TITLE
Husky(v7) fails when .git/hooks directory is missing

### ISSUE THREAD

**Issue by lacell75** [typicode/husky#1003]
Since v7 , I have an error on docker with node 14.17

```yarn install
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning "@wdio/cucumber-framework > @cucumber/cucumber > @cucumber/html-formatter > @cucumber/react > react-markdown@5.0.3" has unmet peer dependency "@types/react@>=16".
[4/4] Building fresh packages...
$ husky install
husky - Git hooks failed to install
spawnSync git ENOENT
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Command failed with exit code 1.
```

**Comment by jrolfs** [comment]
I'm also seeing this in CI, but builds with Husky 6 seem to handle it gracefully? ↓

```sh
husky - not a Git repository, skipping hooks installation
```

**Comment by EvHaus** [comment]
Similar to others, but I'm seeing this error instead after upgrading to v7:

```
$ husky install
.git can't be found (see https://git.io/Jc3F9)
```

This is happening on our CI as well since not all our Docker images there have the `.git` directory. It would be great if `husky`'s installation steps could handle this gracefully and throw a warning instead instead of failing.

**Comment by Heatmanofurioso** [comment]
Exactly the same thing as @EvHaus happening on our projects.
Both on React and Angular-based projects

**Comment by ranisalt** [comment]
Alternatively, most CI services set an environment variable that can be checked to just skip installing the hooks in CI servers.

**Comment by andorfermichael** [comment]
This already happened for me in v6.

There is the section [Disable Husky in CI/Docker](https://typicode.github.io/husky/#/?id=disable-husky-in-cidocker). However, this didn't work because `CI` variable is not set when building in Docker for multi-stage.

The only thing that worked is the following solution https://github.com/typicode/husky/issues/867#issuecomment-840130013 which implies moving the `husky install` from `prepare` to `postinstall`.

**Comment by andorfermichael** [comment]
My pipeline fails because my hooks are running on CI although they should not. Even though I've added .husky to .dockerignore.

[0KRunning with gitlab-runner 14.0.1 (c1edb478)
[0;m[0K  on app2 docker Hx9-RqLc
[0;msection_start:1625563179:resolve_secrets
[0K[0K[36;1mResolving secrets[0;m
[0;msection_end:1625563179:resolve_secrets
[0Ksection_start:1625563179:prepare_executor
[0K[0K[36;1mPreparing the "docker" executor[0;m
[0;m[0KUsing Docker executor with image registry.company.com/company/gitlab-company-runner:latest ...
[0;m[0KAuthenticating with credentials from job payload (GitLab Registry)
[0;m[0KPulling docker image registry.company.com/company/gitlab-company-runner:latest ...
[0;m[0KUsing docker image sha256:1713559830d18d7626d9d982b302266f213d960dd3b6d77bc1bd0ff9deb3224b for registry.company.com/company/gitlab-company-runner:latest with digest registry.company.com/company/gitlab-company-runner@sha256:12605ee264a2ba161af76662e066076ea7f2782538ce3879de5624c195ebc0bf ...
[0;msection_end:1625563181:prepare_executor
[0Ksection_start:1625563181:prepare_script
[0K[0K[36;1mPreparing environment[0;m
[0;mRunning on runner-hx9-rqlc-project-73-concurrent-0 via app2.company.com...
section_end:1625563182:prepare_script
[0Ksection_start:1625563182:get_sources
[0K[0K[36;1mGetting source from Git repository[0;m
[0;m[32;1mFetching changes with git depth set to 50...[0;m
Reinitialized existing Git repository in /builds/company/company-nuxt/.git/
[32;1mChecking out 1bd1bd21 as refs/merge-requests/301/head...[0;m
.husky/post-checkout: line 4: yarn: not found
husky - post-checkout hook exited with code 127 (error)
section_end:1625563184:get_sources
[0Ksection_start:1625563184:cleanup_file_variables
[0K[0K[36;1mCleaning up file based variables[0;m
[0;msection_end:1625563185:cleanup_file_variables
[0K[31;1mERROR: Job failed: exit code 1
[0;m

**Comment by typicode** [comment]
I've published `v7.0.1`. If `git` command is not found, husky should not fail anymore.

**Comment by typicode** [comment]
I've also updated docs with more options for CI/Docker
https://typicode.github.io/husky/#/?id=disable-husky-in-cidocker

**Comment by lacell75** [comment]
Thanks that works now.

**Comment by lacell75** [comment]
> I've also updated docs with more options for CI/Docker
> https://typicode.github.io/husky/#/?id=disable-husky-in-cidocker

I used `HUSKY: 0 in your CI config file` in my CI gitlab config file but with v7.0.0 the husky install was enable .

**Comment by andorfermichael** [comment]
I get the following error now:

`.husky/post-checkout: .: line 2: can't open '.husky/_/husky.sh': No such file or directory`

**Comment by andorfermichael** [comment]
For me the final solution was:
- add .husky to .dockerignore
- replace `"prepare": "husky install"` with `"prepare": "[ -d '.husky' ] && (husky install && shx rm -rf .git/hooks && shx ln -s ../.husky .git/hooks) || true"`
- add to top of hook files
```
[ -n "$CI" ] && exit 0
. "$(dirname "$0")/_/husky.sh"
```

**Comment by deepakthankachan** [comment]
@typicode still getting the same issue with npm 7 (npm 6 is fine)

**Comment by Heatmanofurioso** [comment]
Issue's been fixed for me. Using npm `7.20.1`

**Comment by prebra** [comment]
> I've published `v7.0.1`. If `git` command is not found, husky should not fail anymore.

still getting the same issue with `v7.0.1`

**Comment by surfer19** [comment]
Still same issue for "husky": "^7.0.2",

**Comment by sfc-gh-nlele** [comment]
Hi team, this still fails for husky 7.0.4

**Comment by simonmaass** [comment]
i have the same issue in 7.0.4 - is there any update on how people have solved this?

**Comment by TimRudy** [comment]
Same, with version 7.0.4 - fixed, but not fixed?

**Comment by linong1526** [comment]
It is really too bad. 
Now ,2022/07/21,not fixed ???
Using:
nvm 1.1.9
Node v16.13.0
npm  8.1.0


**> husky install
.git can't be found (see https://git.io/Jc3F9)
npm ERR! code 1**
