### ISSUE TITLE
Why do we need to create the `"prepare": "husky install"` script for `package.json`?

### ISSUE THREAD

**Issue by CodingInvoker** [typicode/husky#1016]
**Context**
This is acutally not a problem while using husky, but rather than a question about npm documentation: https://www.npmjs.com/package/husky

In the documentation, it says that we need to run scripts as below
![image](https://user-images.githubusercontent.com/71058225/127594341-567b3e29-72f2-4e52-88c0-716a521763fb.png)

Is there reason that we want to preserve the script `"prepare": "husky install"` in package.json? I mean it seems like this is only a one time setup scirpt, any benefit of keeping it in package.json?

If we don't need to preserve it in package.json's script field, should it be more straightforward to run `npx husky install` rather than add a `"prepare": "husky install"` script firstly and run `npm run prepare`?

**Comment by Ryuno-Ki** [comment]
In my experience, it's a one-off script. It's easier to remind contributors to run this script once to set up their system accordingly.

**Comment by yordis** [comment]
This is always the dilemma of

1. Everything just works without the required knowledge 
2. I need to learn how things work

If people forget to run the script by, you know, RTFM™️, then what? There is a reason why RTFM exists honestly

**Comment by ElijahLynn** [comment]
I just encountered this (as a devops engineer, not a node engineer) and it seems that the `prepare` section is implicitly invoked by npm/yarn install so therefore it _appears_ that the intent is that when one runs `yarn install` it will run `husky install` and I don't need to update my CI scripts etc.

**Comment by mmounts** [comment]
Just ran into an issue related to this and would love to know the reasoning as well.

For context my team just started using the latest version of Husky (v7) and immediately ran into an issue using `npm ci --production` for our builds.

Now I understand there have been workarounds published: https://github.com/typicode/husky/issues/914, https://typicode.github.io/husky/#/?id=with-npm

But is there an actual reason that these workarounds are being considered the default, correct behavior? Husky is by design a local-dev-only tool, which is why it's installed in `devDependencies` [here](https://typicode.github.io/husky/#/?id=install). So why are users then instructed to save the install script as an NPM lifecycle script (prepare) that is run by default by commands that are intended for CI/CD pipelines (like [npm ci](https://docs.npmjs.com/cli/v7/commands/npm-ci)) and then given workarounds to make those pipelines continue functioning? This seems like it's directly against what the lifecycle method was designed for and should not be encouraged, in case other packages do the same.

It seems pretty backwards compared to either: a) instructing users to set up `husky install` as part of a non-lifecycle NPM script, like `setup`, and instruct new developers to run it at least once, or b) making the `husky install` obsolete.

**Comment by Sandeep-Malhotra** [comment]
I am facing the same issue. I am trying the SAP MTA tool. Deploying the code on Cloud Foundry.

Have tried all the options mentioned in the documentation but no success 

<img width="428" alt="image" src="https://github.com/typicode/husky/assets/11954798/f4a7ba47-fafd-4b80-8756-a81b0fa336aa">

**Comment by GermanJablo** [comment]
I also found the "prepare" script unnecessary. But seeing that husky is a standard with more than 7m weekly downloads, I thought there was a good reason that I didn't know about.

Now reading this thread I'm starting to suspect that maybe I wasn't wrong after all.

I use Husky because I trusted its claim that it adds syntactic sugar, improves DX, and helps avoid common pitfalls. However, following that reasoning, I now wonder if it actually offers any advantage over using Git hooks directly.

Again, husky is so popular and ubiquitous that it makes me think I'm missing something. Could someone explain to me?

**Comment by ryansand20** [comment]
We had a problem where "npm publish" was running the "prepare" step from the published dist folder.
Obviously the .git folder doesn't exist there, so we see this error:
".git folder not found"

We fixed the ability to publish by changing our prepare step to the following:
"prepare": "[ -d '.git' ] && husky install || echo 'skipping husky'"

This checks for the .git folder before trying to setup husky.

**Comment by benallfree** [comment]
+1 for @ryansand20's solution. I was hitting the same problem, except in dependencies. I'm not sure how anyone is publishing a package with `"prepare": "husky install"` when husky is a devDependency. Is there a better npm hook?

**Comment by typicode** [comment]
I think it's related to this https://typicode.github.io/husky/guide.html#custom-directory
Next version will be more relaxed about this.

**Comment by jasonkarns** [comment]
Same concerns as @benallfree. I'm thinking this might be a bug? Husky shouldn't be trying to install during prepare because packages that use husky can then not be installed as git-deps in other projects.

**Comment by sKopheK** [comment]
`git config core.hooksPath .husky` is really needed as `husky` command sets `core.hooksPath` to `.husky/_`

**Comment by jasonkarns** [comment]
This issue is closed and clearly being ignored. We need to open a new issue to get this fixed apparently (and actively fight the stale bot)

**Comment by PaulRBerg** [comment]
The real issue here is that npm doesn't provide a lifecycle script that is run upon running `npm install` locally (as a developer/contributor), but NOT when external users install the package.

The only solution for now seems to be to:

- Remove `husky` from the `prepare` script
- Create a new `setup` script that runs `husky`
- Inform your contributors about the necessity of running `setup`

In the meantime, can one of the Husky contributors confirm that by having `husky` in the `prepare` script, we override our users' git hooks when our package is installed through git?

**Comment by josefanostylus** [comment]
> See https://typicode.github.io/husky/guide.html#disable-husky-in-ci-docker-prod

This link is not working. Could you please provide updated link? 

![Image](https://github.com/user-attachments/assets/5fb6bcf2-3665-4325-9941-372875776b42)

**Comment by Ryuno-Ki** [comment]
I found it in Wayback Machine: https://web.archive.org/web/20231207190412/https://typicode.github.io/husky/guide.html#disable-husky-in-ci-docker-prod

**Comment by caarmen** [comment]
Just some additional info, in case it's helpful:

In case anybody is on yarn 1, from what I see, the `prepare` script [isn't run](https://github.com/yarnpkg/yarn/blob/v1.22.22/src/cli/commands/install.js#L1207) when running `yarn install --production`.

On npm, `prepare` **is** run all the time [since npm v7](https://github.com/npm/cli/pull/8822), as people here already noted.
