### ISSUE TITLE
PR suggestion: add yarn-or-npm as dependency

### ISSUE THREAD

**Issue by elektronik2k5** [typicode/husky#102]
First of all, thanks to @typicode and other contributors for husky! :bowing_man: 
I discovered [yarn-or-npm](https://github.com/camacho/yarn-or-npm) and I think it suits perfectly for husky. Should I add a PR?

**Comment by iamstarkov** [comment]
why?

**Comment by elektronik2k5** [comment]
So you get a consistent task runner: if you've got yarn, use that - otherwise fallback to npm.

**Comment by iamstarkov** [comment]
i see

**Comment by iamstarkov** [comment]
sounds like a good idea

**Comment by onbjerg** [comment]
@elektronik2k5 Are you going to do this or is this open for grabs? Also what does @typicode think? :)

**Comment by elektronik2k5** [comment]
@onbjerg feel free to take this, I don't have the time right now :(

**Comment by onbjerg** [comment]
#126 🎉

**Comment by typicode** [comment]
Hi,

Sorry for the delay and thank you for the PR. I didn't know about this project 👍 

While I'm using yarn for some projects, to keep things simple, I'd prefer to not have to support 2 different runners in husky.

A few issues that could happen too:
- Some people are installing yarn using `npm install -g yarn` (even if it's not the recommended). If they switch to another Node version using `nvm`, the Git hook will fail because it won't find it (unless they reinstall yarn).
- If they remove yarn, they'll have to reinstall husky to update Git hooks.

On the other side, npm is always there.

Also, except if I'm missing, `npm` is fully silenced in husky, if yarn is used instead with `--silent` option, the output will be the same?

That said, It's still possible to make use of `yarn-or-npm` in `precommit` script:

```json
{
  "precommit": "yarn-or-npm test"
}
```
