### ISSUE TITLE
Support other shells ex: zsh

### ISSUE THREAD

**Issue by rhuanbarreto** [typicode/husky#1025]
**Troubleshoot**
- [x] Before creating an issue, please check: https://typicode.github.io/husky/#/?id=troubleshoot

### Context
Today husky install scripts using bourne shell `sh`. Most of the mac users use Z Shell by default `zsh`.

### Workaround
Changing the shebang from `#!/bin/sh` to `#!/bin/zsh` fixes fixes 2/3 of the problems in the troubleshoot section if you have mac.

### Request
Is there a way for husky to identify this and use the shell in the shebang at the start of the scripts?
Maybe having a config during `husky install` to choose the shell would help the mac users.

### Why this is useful?

Problems as [Command not found](https://typicode.github.io/husky/#/?id=command-not-found) would not happen once all the profile configuration sits in `~/.zshrc` file. Loading zsh in the script file would remove totally the need for this section.

**Comment by typicode** [comment]
Hi,

`sh` is used for portability as it's available on Windows, Linux and macOS. Using `zsh` by default would create issues for Windows users, that's why this choice was made.

That said, if you're working in a team and know that everyone has `zsh`, you may call a `zsh` to run your script (I haven't tested the code below):

```sh
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

zsh ...
```

Alternatively, you can completely replace `pre-commit` content with your own code and make it executable, if you need greater control.

**Comment by rhuanbarreto** [comment]
Just to clarify the request. I understand that bourne shell is a default. I just proposed something like:

`SHELL=zsh husky install`

And then zsh would be the shell used for any husky command/hook.

**Comment by typicode** [comment]
> Just to clarify the request. I understand that bourne shell is a default.

Yes, I was a bit too fast in reading the issue and answering, that's why I deleted my previous comment.

In my experience, it's a tricky topic. Maybe there's a way, but I feel having different shell support would bring complexity and harder to debug issues. Especially hook syntax would then need to be compatible with different shells (`zsh`, `fish`, etc...).

**Comment by rhuanbarreto** [comment]
Say that the support to another shells are experimental and people should use it at their own risk.

FYI `sh` and `zsh`are quite the same. Zsh is an extension of sh. They use the dot command to load files instead of `source`, so there won't be any bigger issues.

**Comment by davidwincent** [comment]
You can start another shell and pass all arguments with this command:

```sh
# Change interpreter to bash because Bourne shell is old and doesn't support regex
/usr/bin/env bash scripts/git-commit-msg.sh "$@"
```
