### ISSUE TITLE
[RFC] Parse a Config File Into Hooks

### ISSUE THREAD

**Issue by mmcxii** [typicode/husky#1047]
## Proposal

I'd like to add a feature that will allow Husky users to use a config file to generate their git hooks, while avoiding the issues that caused Husky to drop support for these config files in version 5. I would propose that an optional flag be added to the `husky install` command called `--fromConfig`. If enabled, this flag would attempt to parse a Husky config file located in either the root of a project or in the .husky folder where the resulting hooks are to be stored. If a config is found, the `husky set` command would then be ran for each hook in the config file.

With this solution, the git hooks are still ran from a pure executable script file. However this would enable a configuration file to be shared across an infinite number of projects.

## Sample code

Here is a code snippet for how I have implemented this behavior locally in my own CLI tool. It should be fairly straight forward to migrate this into husky's codebase.

```ts
// install-hooks
import cp from "child_process";

function installHooks(): void {
  // Attempt to find git hooks from a config file
  const hooks = getHooks();

  // If no hooks are found, abort the process.
  if (hooks == null) {
    return;
  }

  // Iterate over each hook and create a corresponding file in the .husky folder.
  for (const [hook, action] of Object.entries(hooks)) {
    cp.execSync(`npx --no-install husky set .husky/${hook} "${action}"`);
  }
}

// get-hooks
import p from "path";
import { cosmiconfigSync } from "cosmiconfig";

function getHooks(): null | Record<string, string> {
  const explorer = cosmiconfigSync("husky");

  // Attempt to find a config in the current working directory.
  const cwdSearchResult = explorer.search(process.cwd());
  if (cwdSearchResult?.config != null) {
    return {
      ...cwdSearchResult?.config?.hooks,
    };
  }

  // Attempt to find a config in the .husky directory.
  const huskyDirSearchResult = explorer.search(p.join(process.cwd(), ".husky"));
  if (huskyDirSearchResult?.config != null) {
    return {
      ...huskyDirSearchResult?.config?.hooks,
    };
  }

  return null;
}
```

## Next steps

Really I'm posting this to gauge interest from the maintainers and see if this is even something they'd be willing to have in their project. If so, I'll be happy to spin up a PR likely next week in hopes we can get this out sooner than later. I'd also want to understand the test scenarios required and make sure it gets vetted properly.

**Comment by k2snowman69** [comment]
It's been a few months and we're heading into holiday season which I usually have some spare hours I can dedicate. @typicode have you had time to take a look at the RFC yet?

**Comment by k2snowman69** [comment]
@typicode got hit with the stale bot, waiting on you to greenlight the idea.

**Comment by typicode** [comment]
Thanks a lot for your patience.

I haven't documented it yet, but it's possible to do this instead:

```js
// husky.config.js
const husky = require('husky')
husky.install()
husky.set('.husky/pre-commit', 
`// Generated, do not edit
npm test`)
```

```
node husky.config.js
```

`.gitignore` can be edited to ignore `.husky/` since it's generated code.

However the downside of using a config file is that the source of truth moved to a JS file. You then need to re-synchronize Git hooks when there's a change in `husky.config.js`.

With having scripts in Git hooks (i.e. `.husky/pre-commit`), there's no additional step. If a team member updates the hook script, everyone in the team gets the new hook automatically.

I guess it's a tradeoff between having a single file/manual updates and more files/automatic updates.

Because of that, I prefer not to support config files in husky.

That said, husky can be used programmatically for such case, to provide more flexibility.  If it suits better your case, feel free to create a tool that reads a config file and calls husky API :)

By the way, if you have one or two hooks, you can also have them at them at the root of your project if you prefer not to have a `.husky` directory (`husky install . && husky add ./pre-commit 'echo foo'`).

**Comment by k2snowman69** [comment]
The core reason I was interested in having a single npm package contain the config is so that I can update the shared npm package once and have tools like Renovate or Dependabot roll out updates to each repo individually. 

You're right, every time someone does an npm install which could possibly update that shared npm package, they would need to re-create all the hooks but that's simple enough to hook up via a post-install script. 

It's less about one person updating a hook in a single repository and more about updating a hook across n repos. With it being a shareable config, it's much easier to roll out due to existing tooling than manually making a git commit change across n repos. 

That said, it's your repo with your decisions. The information you provided in how we can run husky via code will clean up our wrapper tool quite considerably so thanks!
