### ISSUE TITLE
'husky install' fails if '.git' directory does not exists

### ISSUE THREAD

**Issue by BricePissard** [typicode/husky#1084]
If you have a large project, we can't install Husky anymore. Only small projects can install it now... 

in a repo:
- myRepo/.git
 -- ./myRepo/back/package.json
 -- ./myRepo/front/package.json

```
cd ./myRepo/back
yarn add husky -D
npx husky install
```

`throw new Error(".git can't be found");`

The bug still exists in 7.0.4, (#851) could you please place a recursive test to check if the .git folder exists in the parent, then parent's parent, then parent's parent's parent... folder.

In the real world, it happens that the GIT is a mono-repo that contains differents folders with different projects with a package.json in each.

**Comment by mateuszklinowski** [comment]
Hello!

Do no custom directory section of documentation take care of exactly this case?
https://typicode.github.io/husky/#/?id=custom-directory

**Comment by AnubisAwooo** [comment]
> 

Thank you.

**Comment by thany** [comment]
I ran into this as well, and I was baffled to why this requires a custom directory config. This my case, and in BricePissard's case, the `.git` directory is not in a custom location, but rather in a perfectly reasonable and default location. It's completely normal for the `.git` directory to be one or more levels up.

Looking for it should be fully automated. In the same way theat any `git *` command works anywhere in the dorectory structure, as long as somehwere in a parent or ancestor folder the `.git` directory can be found, indicating the presence of a git project.

**Comment by typicode** [comment]
It's on purpose because of two issues that happened:
1. Imagine you have a Python project and download a JS Open Source project as zip or tar. You proceed to run `npm install`, if husky recursively checks for .git then it can create issues with existing git hooks.
2. Some users also go to node_modules/some_project and run `npm install` inside them to quickly try things.

Also some users believe that `package.json` dependencies should not go below `package.json` root directory.

I understand it can be annoying and there's no universal solution. However the choice was made with husky 7 to lean on the side of safety and being more explicit where hooks should be installed by not allowing `..` in the install path.

That said as @mateuszklinowski mentioned, you can `cd .. && husky project/.husky`.  There's also a section for monorepos.

Hope it helps and clarifies the reasoning behind it :)

**Comment by mario-d-s** [comment]
@typicode wouldn't it be more convenient to have a flag for `husky install` that explicitly allows it to search for the `.git` directory upwards recursively? This would already be much more convenient than having to `cd ../../..` to the correct level.

In my case it's even harder cause I'm integrating Husky as part of a project template, where the template cannot know where the `.git` directory will eventually be - it's supposed to be some levels up, but how many levels is not known beforehand.

**Comment by David245M** [comment]
@mateuszklinowski The link is not leading anywhere, could you update it?
