### ISSUE TITLE
'husky install' fails on a Serverless deploy because there is no .git folder

### ISSUE THREAD

**Issue by carlosdnba** [typicode/husky#1090]
I am still facing issue #851 when deploying a Serverless app.
The content of the Serverless folder after running `npm install` is only:

```
drwxr-xr-x    5 carlos  staff      160 Jan  9 14:43 .
drwxr-xr-x    3 carlos  staff       96 Jan  9 14:43 ..
drwxr-xr-x  164 carlos  staff     5248 Jan  9 14:43 node_modules
-rw-r--r--    1 carlos  staff  1869687 Jan  9 14:43 package-lock.json
-rw-r--r--    1 carlos  staff     4480 Jan  9 14:43 package.json
```

Since it's a deploy, but not a CI environment, I couldn't find anything useful on husky docs to sort this out.

<img width="895" alt="Screen Shot 2022-01-09 at 2 51 48 PM" src="https://user-images.githubusercontent.com/64426814/148694218-c78252a5-5bc6-459e-916a-e82160e87a2b.png">

**Comment by trasherdk** [comment]
`husky` | Modern native **`Git`** hooks made easy

The `git` part is key :smiley:

**Comment by carlosdnba** [comment]
Although I see and agree, I think the package could find a way to identify if the package installation is happening in an environment without git, and not throw an error.

**Comment by typicode** [comment]
Hi @carlosdnba 

Let me know if I'm missing something or making a mistake.

The installation happens in an environment where Git is installed and we're in a repo, husky checks for that here:
https://github.com/typicode/husky/blob/main/src/index.ts#L16

The issue here is that `husky install` is running in a sub directory (below .git).

The fix would be:
https://typicode.github.io/husky/#/?id=custom-directory

Also it's not possible to detect every environment and cases (too complex or there's simply no env variable for that), if the above link doesn't help, try disabling husky or ignore errors using a custom script:
https://typicode.github.io/husky/#/?id=disable-husky-in-cidockerprod

**Comment by JanFellner** [comment]
Sadly same issue here.

I am installing a package from a private repo. In that package we have a package.json that contains
"postinstall": "husky install"

when i try to add this package as dependency in another it fails as husky install complains about not finding a .git folder.

`
X:\dev\product>npm i package
npm ERR! code 1
npm ERR! path X:\dev\product\node_modules\depdendend_package
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c husky install
npm ERR! .git can't be found (see https://git.io/Jc3F9)
`

**Comment by typicode** [comment]
@JanFellner I'd recommend using `prepare` instead of `postinstall`. `prepare` will only run in "development", whereas `postinstall` will always run (even when the package is installed in `node_modules`).

**Comment by JanFellner** [comment]
@typicode thanks for the hint. Changed it accordingly looking gooood ;]
