### ISSUE TITLE
Cannot rely on return code due to "-e" option in husky.sh

### ISSUE THREAD

**Issue by cupidchan** [typicode/husky#1142]
In my pre-commit script, I rely on `grep -E '(.ts$|.html$|.js$|.yaml$|.yml$|.md$)'` to determine the appropriate action based on file types. However, when grep cannot find the result, it will have a return code of "1". When this happens, Husky will catch and end the process, even though I have logic to handle this situation. 

When I reviewed the code, I found out the reason is pre-commit calls husky.sh in the first line. And inside husky.sh, there is a line `sh -e "$0" "$@"` the "-e" option will make the shell exit immediately if a command exits with a non-zero status. Why is is option required? If the "-e" option is not here, the script can have a better control to handle situation like this. 

In the meantime, I temporarily disable calling husky.sh, but I saw some comments that is useful for "GUI users cloning the project". I am wondering how does that work and if there may be any unknown side-effect if I comment that out.

Thanks a lot!

**Comment by typicode** [comment]
Hi @cupidchan,

You can disable it with:

```sh
# ...
set +e
# ... do something
set -e
```

The `-e` option is used so that people can write code like this and have the hook automatically fail without extra code:

```sh
# ...
npm run lint # if lint fails, hook will fail as well
npm test
```

**Comment by cupidchan** [comment]
Yes, that resolves the issue. Thanks  a lot for your quick reply @typicode!

**Comment by keithlayne** [comment]
Sorry to pile on here, but I just ran into this today, and I felt really dumb because it took me a while to realize that `set -e` was on even though my hook didn't set it.

I just looked through the docs, and I don't see anything about it. I think it would be really useful to call out the `husky.sh` environment in the docs. I think (guessing) it's a not-uncommon thing to have existing git hooks that you bring to husky. In this case, some are gonna break non-obviously (well, pretty obviously if you're not dumb like me).

I think a "migrating hooks to husky" note or something in the docs could be a good way to handle this, or an entry under troubleshooting.
