### ISSUE TITLE
set-script deprecated

### ISSUE THREAD

**Issue by louwers** [typicode/husky#1150]
`npm set-script` is deprecated and should probably not be recommended in the docs anymore: https://docs.npmjs.com/cli/v8/commands/npm-set-script

**Comment by typicode** [comment]
Thanks for the heads-up. The command didn't last long.

**Comment by immayurpanchal** [comment]
The documentation has still old command of npm set-script. The issue should be re-opened.

**Comment by TheJaredWilcurt** [comment]
Because this is the first Google result for `npm set-script deprecated`, I thought I'd hijack it to save people some time:

Change your code from this:

```
npm set-script start "nw ."
```

to this

```
npm pkg set scripts.start="nw ."
```

As the [author of the original RFC](https://github.com/TheJaredWilcurt/rfcs/blob/23896ac6eaa172036f90ca5d8ed935708b8a0493/accepted/0000-add-script-command.md) for `set-script`, I'm fully in favor of this more versatile approach.

**Comment by yuvalbl** [comment]
Thanks @TheJaredWilcurt  :)
