### ISSUE TITLE
Too many repeat ouput when run husky hooks on WIN11 

### ISSUE THREAD

**Issue by HaiLin545** [typicode/husky#1173]
<img width="498" alt="image" src="https://user-images.githubusercontent.com/56110784/179348929-4439bff6-c544-482b-8732-80b467dceae6.png">

I think is the shell did not support for the loading animation , can any one helps? Thank you !

**Comment by mahisat** [comment]
In windows 10 also faced same issue. I think the issue is related with [lint-staged](https://www.npmjs.com/package/lint-staged) library. I faced similar issue with [lint-staged@13.0.3](https://www.npmjs.com/package/lint-staged/v/13.0.3) and downgraded it to [lint-staged@12.5.0](https://www.npmjs.com/package/lint-staged/v/12.5.0). Now it's working fine for me.

**Comment by HaiLin545** [comment]
> 

You are right. It was the trouble with lint-staged.
