### ISSUE TITLE
Discussion: what would take us to build and ship husky to a v1?

### ISSUE THREAD

**Issue by piperchester** [typicode/husky#119]
Noticed we're still at 0.13.x... anything holding us back?

**Comment by jhabdas** [comment]
It would take a major release. It's that simple. And you _should_ do it because people use you for their production products now that `ghooks` has been deprecated. Please cut a major.

http://semver.org/#how-do-i-know-when-to-release-100

If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.

**Comment by voxpelli** [comment]
Husky should already be considered to be a stable release due to the amount of people using it – thus it makes sense to release a 1.0 as has previously been pointed out.

That + have any future breaking changes result in a bump of the major version would be 🥇 👍 

Anything new on this front since this issue was created?

**Comment by voxpelli** [comment]
Noticed that #195 points out that it may become the v1, so seems like something has indeed happened on this front.

**Comment by typicode** [comment]
Still behind `next` tag but https://github.com/typicode/husky/releases/tag/v1.0.0-rc.1 :wink:
