### ISSUE TITLE
Stop pre-push hooks

### ISSUE THREAD

**Issue by dsousa12** [typicode/husky#1206]
Hi guys
I have an alias on my `.zshrc`  to run `git add . ` + `git commit -m "message"` + `git push`.
My question is:
- if one of the **Husky** hooks fails, is possible to prevent the running of the other hooks?

Because at this moment, if `pre-commit` fails the `pre-push` runs any way.

**Comment by FilipMaslovaric** [comment]
> if one of the Husky hooks fails, is possible to prevent the running of the other hooks?

No, given the information you've provided - it isn't likely possible, because its not Husky, or Git, or the Git Hooks that are causing `pre-push` to "run any way" but how you're executing the commands inside of `.zshrc`.

You'll most likely need to add some error handling and conditional logic to check whether the current command running (e.g. the `git commit` command, and the `pre-commit` hook script it would run when executed) are exiting with an error, e.g. `exit 1` rather than `exit 0`.

If you aren't using any conditional logic or error handling, chances are that `git commit` and `pre-commit` are just failing silently, and your code is just then running the next command in the sequence, `git push` (and therefore, `pre-push`).

**Comment by typicode** [comment]
`&&` should do the trick: `git add . && git commit -m "message" && git push`
