### ISSUE TITLE
Shellcheck complains about hook script

### ISSUE THREAD

**Issue by TrevorBurnham** [typicode/husky#1226]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/#/?id=troubleshoot

**Context**
(This is a minor issue: Functionality isn't affected.)

Scripts generated by `husky add` contain the line:

```sh
. "$(dirname -- "$0")/_/husky.sh"
```

Shellcheck, the popular shell script linter, doesn't care for that line. It complains:

```
Not following: ./_/husky.sh was not specified as input (see shellcheck -x). shellcheck(SC1091)
```

The rule in question, [SC1091](https://www.shellcheck.net/wiki/SC1091), is complaining about Shellcheck not being able to access the referenced file. I can't think of a way to satisfy the rule, so it may be that the best solution is to have `husky add` emit a `shellcheck disable` directive above it:

```sh
# shellcheck disable=SC1091
. "$(dirname -- "$0")/_/husky.sh"
```

Of course, another solution would be for developers to simply ignore the warning, but I believe it's very common for devs who use VS Code to have the Shellcheck extension installed (it has 500,000+ downloads) and enabled by default, so an extra line to silence the warning might avoid some confusion. Or maybe there's a more Shellcheck-friendly way to run `husky.sh`.

**Comment by paescuj** [comment]
Hey @TrevorBurnham, thanks for raising this issue!

Actually, the problem here is that the VS Code extension is spawning `shellcheck` without the `-x` / `--external-sources` by default, which means `shellcheck` isn't following external files at all.
The warning goes away when running `shellcheck` with the option mentioned above or by specifying the source file explicitly. That is, `shellcheck` is able to follow the file in that case without the need for a directive.

I do realize that this might be confusing for devs who have the VS Code extension installed, but I feel like it's simply wrong to disable the check here.
In fact, I think the more sensible solution would be to raise an issue at https://github.com/vscode-shellcheck/vscode-shellcheck asking to turn on the `-x` / `--external-sources` by default.

That being said, your report inspired me to go through all shell scripts in this repo and fix the reported issues by `shellcheck` where applicable (see #1230).

**Comment by TrevorBurnham** [comment]
Thanks for getting back to me! I've raised the issue with the vscode-shellcheck folks: https://github.com/vscode-shellcheck/vscode-shellcheck/issues/883

**Comment by paescuj** [comment]
Nice, thank you!
