### ISSUE TITLE
Unable to use Husky on Windows when also using NVM

### ISSUE THREAD

**Issue by mickeypuri** [typicode/husky#1302]
I've created a new npm project and have tried to run husky. 

Doing everything as per the book, installing Husky, but then the pre-commit hook fails to run. Looking thru it seems there is an issue with nvm. Have tried the suggested script, and putting it in the root directory, but that fails to do the trick. Looking thru the script code, its looking for a .nvm file which is not present either, so it was not going to run. 

So am having to drop the idea of using Husky till a fix is found, as we are using NVM due to different projects needing different node versions.

**Comment by typicode** [comment]
Nothing that can really be done on husky's side. Not that it's a bug directly.

I've never used nvm on Windows so I don't know if the code provided in the docs is different. You may want to check how nvm is loaded in your terminal and try putting this code in your ~/.huskyrc file (it needs to be POSIX compliant though). You can also set HUSKY_DEBUG=1 environment variable to ensure that ~/.huskyrc.

**Comment by Blindman139** [comment]
There is one solution/workaround to this.
NVM (at least for windows) creates a symlink to the node version that we choose. And for me it was at the location "C:/nvm4w/nodejs". (You can deep dive into system Path variables and see how this location is added in the list so that command 'node' can be executed in cmd)

Now, about husky, it was trying to find node executable at location "c:/Program Files/nodejs". 

What I did was,
Created symlink of "c:/nvm4w/nodejs" in to "c:/Program Files/nodejs"
By executing below command in Program Files location.
```
mklink /d nodejs "C:\nvm4w\nodejs"
```
