### ISSUE TITLE
Docs: explain benefits better

### ISSUE THREAD

**Issue by xenoterracide** [typicode/husky#1306]
Could a document be written explaining why I should use husky better? It seems these days all it's really doing is setting `core.hooksPath`. I see "features" but none of that really says why this is better than just setting that using the git cli.

**Comment by careless6666** [comment]
I would say that the concept of not allowing commits is generally terrible. It is much more effective to check the code in ci and not allow bad code to merge.

1) I can always commit my work, and then add something and not send it for review
2) I don’t spend a lot of time fixing errors before committing, I can make a prototype and only then decide if it works in k8s and one of the participants poked it, whether it’s worth merging and finishing it
3) there are no problems with errors, like the flow of hooks is broken and my changes can be put on a shelve
4) there are no strict guarantees, because users can disable hooks when committing

**Comment by xenoterracide** [comment]
Aren't all of those things true without husky?

**Comment by careless6666** [comment]
Yes, without a husky there are no above problems

**Comment by typicode** [comment]
@xenoterracide Thanks for the feedback. If I have the time to, I will (no promises though :). Meanwhile, you can check the discussions or code to have an idea what else it's doing. There are articles as well.

@careless6666 set `HUSKY` env variable to `0` and no hooks will ever run ;)
