### ISSUE TITLE
Provide backwards config compatibility

### ISSUE THREAD

**Issue by jhabdas** [typicode/husky#133]
When `ghooks` deprecated in favor of this project it left a lions share of manual work. While it may seem inconsequential to the owners and collaborators of this project, it would be less work for `husky` to provide backwards compatibility than the man-hours which will be spent updating configuration.

For context, here are the current download statistics for the popular `ghooks` library:

<img width="358" alt="screen shot 2017-06-04 at 6 38 19 pm" src="https://cloud.githubusercontent.com/assets/440298/26760853/0dbc0338-4955-11e7-9c29-d0ad897ec524.png">

The above metrics signify just some of the many individuals which'll need to update their package manifests as the NPM deprecation notice drives upgrades to `husky`.

Backwards compatibility has the added benefit of allowing users to keep their `scripts` free and clear of cruft dev dependencies might want to add because NPM does not support the likes of [an `extra` field](https://getcomposer.org/doc/04-schema.md#extra) in the package manifest.

As an alternative, and something [`standard`](https://github.com/feross/standard) does, you may want to consider providing a `husky` object at the root of the package manifest to help eliminate the need for clobbering `scripts` until NPM provides an appropriate solution for the problem current design attempts to achieve by eschewing use of `package.config`.

And as an aside, it is my opinion **reserving `scripts` as a sacred ground specifically for package author use is important**, and that's something this library currently does not provide.

It would be a pleasure to hear the community weigh in.

**Comment by jhabdas** [comment]
No traction. Closing.

**Comment by jhabdas** [comment]
Returned to `ghooks`. I've already got a `lint` script. I don't need a `precommit` script to run my `lint` script. Thanks. 🤣

**Comment by jhabdas** [comment]
@typicode fyi - https://github.com/ghooks-org/ghooks/issues/209

**Comment by typicode** [comment]
Hi @jhabdas,

First, sorry for the lack of answer. To be honest, I don't always have the time to reply to all (even though I would really like to!) but I try to address them at some point or the community does.

For `ghooks` compatibility, actually I didn't see the benefit of supporting `ghooks` fields in `husky`, since they are 2 different projects and would force to maintain 2 styles of configuration.
Also I may miss something, but switching is just a matter of updating 2 or 3 lines?

`husky` could automatically update `package.json` to move `ghooks` scripts to `scripts`, but I would feel it kind of intrusive for a package to do that (maybe it's not but I'm not aware of tools that do that automatically).

That said, to make it easier for users, existing `ghooks` scripts in `.git/hooks` are automatically migrated.

Regarding where to put them, I prefer them to be with other npm scripts and npm hooks (but that's a personal opinion).

If `ghooks` suits you better, that's cool :) :+1:

Regarding another topic that was raised, `precommit` vs `pre-commit` syntax, I'm considering switching to the latter but I'm currently working on a new version in `next` branch which should improve some other things

**Comment by jhabdas** [comment]
> For ghooks compatibility, actually I didn't see the benefit of supporting `ghooks` fields in `husky`

Sorry if it wasn't clear, but my main concerns were actually easing the upgrade path and not clobbering scripts. That could also be achieved by simply changing `pkg.config.ghooks` to `pkg.husky` and respecting the format.

> I would feel it kind of intrusive for a package to do that

Agreed. Automated or manual (current) it feels intrusive.

> That said, to make it easier for users, existing `ghooks` scripts in `.git/hooks` are automatically migrated.

Nice touch.

> To be honest, I don't always have the time to reply to all...

Hope you're able to prioritize the migration over feature development as that's where most users could use you at current due to the `ghooks` deprecation, which, now that I'm a part of their org, am actively trying to undo.

> If `ghooks` suits you better, that's cool

I'd rather be using the more feature-rich and well-supported product, personally. And that's why I tried `husky` but as mentioned above I'm not willing to clobber my `scripts` object. That would result in stuff like this:

```json
"scripts": {
  "pre-push": "npm run lint"
  "lint": "standard"
}
```

And that just feels dirty to me. Which is why I opened this issue as I saw a win-win saving people time and creating a design which suited the needs of multiple hook managers.

---

At any rate, best of luck with the upgrade. Looking forward to learning from husky over time a I work with the community to help revive the `ghooks` library and use the opportunity to spin it in a complimentary direction.
