### ISSUE TITLE
How to hide this message on CLI "add --no-verify to bypass" ?

### ISSUE THREAD

**Issue by jitendravyas** [typicode/husky#135]

**Comment by chaosforfun** [comment]
can we add a config like this to hide the tip.
"husky": {
        "hooks": {
           ....
        },
        "bypassTIp": false
    },

**Comment by astenmies** [comment]
A silent exit 1 can be done with `exit 1 > /dev/null`.

So you can add that at the end of your bash script, or have add it at the end of the command in package.json.

**Comment by metasean** [comment]
@astenmies - re: "That tutorial also solved my problem of `--no-verify` to `bypass` simply because it successfully did the job without having to prevent the normal git behaviour."

I'm not seeing anything in the link that you posted which addresses this, but it sounds like it's exactly what I'm looking for.  By chance, do you think you can find and share the actual page from your browser history.  (Neither my duckduckfoo or googlefoo are finding anything other than your comment.)
