### ISSUE TITLE
zsh throw error when use husky hooks

### ISSUE THREAD

**Issue by iulo** [typicode/husky#1411]
iterm2 with zsh, mac m1, husky@9.0.1

get wired error log when commit, have no idea what happend. Appreciate any help
```log
/Users/iulo/.zshrc: line 4: ${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh: bad substitution
/Users/iulo/.zshrc: line 101: autoload: command not found
Error: Oh My Zsh can't be loaded from: sh. You need to run zsh instead.
Here's the process tree:

 PPID   PID COMMAND
    1  1702 /Applications/iTerm.app/Contents/MacOS/iTerm2
 1702  1752 /Users/iulo/Library/Application Support/iTerm2/iTermServer-3.4.23 /Use
39594 18944 git commit -m readme
18944 18945 sh .husky/_/pre-commit
 1752 39593 login -fp iulo
39593 39594 -zsh

/Users/iulo/.zshrc: line 300: compctl: command not found
/Users/iulo/.zshrc: line 354: `yarn-link-list': not a valid identifier
```

**Comment by typicode** [comment]
Hi,

What's the content of .husky/pre-commit?

**Comment by iulo** [comment]
@typicode just a simple echo `echo "test pre-commit"`

**Comment by iulo** [comment]
no idea why I have a `.  ~/.zshrc` in ~/.config/husky/init.sh， remove it and everything works fine

**Comment by rujmah** [comment]
@iulo thanks, took me ages to figure out this one.

My ` ~/.config/husky/init.sh` also had `. ~/.zshrc`. Removing it also fixed my issue 🙌 

It looks like I may have set it a while ago due to this [help item](https://github.com/typicode/husky/blob/0692639896ea5b5dd5ffc607575f6f870b21cb0f/docs/how-to.md#node-version-managers-and-guis) about configuring husky with `nvm`.
