### ISSUE TITLE
Husky git hook with lint-staged not working

### ISSUE THREAD

**Issue by RatikantS** [typicode/husky#1417]
I have just added "npm run test" to git commit hook, its failing with below error (refer the snapshot) - seems the matching files are being passed as argument?

"husky": "^8.0.3",
"lint-staged": "^15.2.2",

Config in .lintstagedrc file:

```
{
    "src/**/*.{js,ts}": [
        "npm run test"
    ]
}
```

![image](https://github.com/typicode/husky/assets/148453101/994b711c-92c8-4951-a244-bb164340d7aa)

**Comment by TobiTenno** [comment]
yes, that is how lint-staged works in general. you can ignore them by providing a lambda in your config instead of a json-formatted config file, like in lint-staged's [ts example](https://github.com/lint-staged/lint-staged#example-run-tsc-on-changes-to-typescript-files-but-do-not-pass-any-filename-arguments)
