### ISSUE TITLE
Trying to grep from the input COMMIT_EDITMSG file in a hook fails

### ISSUE THREAD

**Issue by endika-campo** [typicode/husky#1455]
**Context**

When trying to grep from the input `COMMIT_EDITMSG ($1)` file in the `prepare-commit-msg` hook makes it fail without any relevant trace nor error message.

- The version of terminal is zsh 5.9 on a Mac
- Husky version 9.0.11
- Try to grep from the $1 input variable in the aforementioned hook. It doesn't execute the hook as it fails on that line.

You have the following code I am currently using on my prepare-commit-msg. It executes correctly until it reaches line `COMMIT_TYPE_PRESENT_IN_MESSAGE=$(echo $COMMIT_MESSAGE | grep -Eo "^(${COMMIT_TYPE_LITERALS}):")`. 

I have correctly extract the contents of the $1 file with cat, but as soon as I try to grep anything from it, the hook fails.

```
#!/bin/sh

COMMIT_TYPE_LITERALS='feat|fix|docs|style|refactor|test|chore|perf|test|build|ci|chore|revert'

BRANCH_NAME=$(git symbolic-ref --short HEAD)
TICKET_ID=$(echo $BRANCH_NAME | grep -Eo 'CU-.{9}')
COMMIT_TYPE=$(echo $BRANCH_NAME | grep -Eo "^(${COMMIT_TYPE_LITERALS})")
COMMIT_MESSAGE=$(cat $1)

COMMIT_TYPE_PRESENT_IN_MESSAGE=$(echo $COMMIT_MESSAGE | grep -Eo "^(${COMMIT_TYPE_LITERALS}):")

if [ $COMMIT_TYPE_PRESENT_IN_MESSAGE ];
then
    CLEAN_COMMIT_MESSAGE=$(echo $COMMIT_MESSAGE | grep -E "^(${COMMIT_TYPE_LITERALS}):" | sed 's/^.*://')
    sed -i.bak -e "s/.*:/$COMMIT_TYPE_PRESENT_IN_MESSAGE $TICKET_ID | /" $1
else
    sed -i.bak -e "1s~^~$COMMIT_TYPE: $TICKET_ID | ~" $1
fi
```

**Comment by typicode** [comment]
Probably too late. But what if you add `set +e`?

**Comment by endika-campo** [comment]
> Probably too late. But what if you add `set +e`?

Where specifically?

**Comment by typicode** [comment]
At the top

```
#!/bin/sh <- this can be omitted by the way
set +e
```

**Comment by endika-campo** [comment]
That works as a charm @typicode! Thanks so much! Would you mind telling me what have I done to fix it? Don't really understand what was the issue, nor what have I done to fix it... xD And again thx!

**Comment by typicode** [comment]
Sure, so `set -e` changes behavior of the hook script so that any command exiting with non-zero makes the entire script fail (if grep doesn't find find something it exit with non-zero).

Most of the time, this behavior is wished for simple scripts (like if the content of `pre-commit` is `npm test').

But if you're writing a much more complex script, like yours you may wish to disable it with `set +e`.
So now, in your script, unless you call `exit 1` explicitly, your `prepare-commit-msg` will never fail (it may or may not be something that you want).
