### ISSUE TITLE
only check sibling projects with changes

### ISSUE THREAD

**Issue by andykais** [typicode/husky#160]
related to issue #134, but on a related problem. If I have the structure:
```
project/.git
project/client/package.json
project/server/package.json
project/admin/package.json
...
```
If I use the `precommit` script in `client/package.json` and change code in `admin/`, then the precommit script will be ran in `client/` regardless of whether or not there are changes in that subfolder. I propose that the husky find a way to store the hooks for multiple subprojects (like in #134 ) AND only run them if there are changes staged by git in the folder containing the package.json with the husky scripts

**Comment by SuEric** [comment]
I'm also looking for this :/

**Comment by typicode** [comment]
Hi @andykais,

TBH I don't really see how it could be done in a simple manner.

A few questions would need to be solved:
* When you uninstall husky from a project it would have to remove the reference to the project
  * If it's the last place where husky is used it should also remove all hooks
* What about multiple version of husky and therefore multiple version of hook scripts and if you uninstall a version
* ...

It may not perfect but you could have this:

```js
// Create project/package.json
// and add husky here
{
  "scripts": {
    "precommit": "cd client && npm run precommit"
  }
}
```

This way you have one central point where you can handle hooks.

If you want to automate it further:

```js
// project/client/package.json
{
  "private": true,
  "scripts": {
    // DON'T do this if it's a module that is published on npm
    // this will ensure that husky is installed using projects/package.json
    "postinstall": "cd .. && npm install",
    "precommit": "npm test"
  }
}
```

The only thing to be careful is that if you publish the project on npm, people installing it will get errors with postinstall.

**Comment by SuEric** [comment]
This doesn't sound like a solution, neither a work around. I don't get why doing `cd .. && npm install` ... That wouldn't work for multiple folders where each folder represent different things.

For example I've Backend and Frontend folder. Each of them has a `package.json` file.
Maybe husky should create N hooks? and put ea hook point to the  right folder `package.json`? 
I don't know how doable is that but I'm open to help

**Comment by typicode** [comment]
@andykais I would say it would be quite complicated to maintain as sub-projects can be deleted, renamed, moved, ... fortunately, there are tools to manage monorepos :)

I would recommend using [`lerna`](https://github.com/lerna/lerna) + `husky` if you have multiple packages.

lerna comes with ways to run commands only for packages that have changed since "master" for example:
https://github.com/lerna/lerna#--since-ref

There are some documentations for `lerna + husky` [here](https://github.com/typicode/husky/blob/dev/docs.md#multi-package-repository-monorepo) (please note it's for the beta version of husky, but it can be applied to the stable one as well)
