### ISSUE TITLE
Disabling nvm use

### ISSUE THREAD

**Issue by screendriver** [typicode/husky#183]
It seems that it is not possible to disable an automatic `nvm use`. For example I have a `prepush` commit and I want to ensure that everyone uses the same Node version. But what I don't want is to automatically use `nvm use` when I push because that would enforce to reinstall all dependencies and run the complete build.

So would it be possible to just disable the automatic nvm use and just warn the user that it has to use the given Node version?

**Comment by gdumitrescu** [comment]
Try the engines option in package.json `https://docs.npmjs.com/files/package.json#engines` and then add `engine-strict=true` option in .npmrc `https://docs.npmjs.com/files/npmrc` with `npm config set engine-strict true`.

**Comment by TinOo512** [comment]
I would love to have that also. We are using the same version of node and it's just slowing the pre-commit hook.

I can open a PR to handle an environment variable `HUSKY_SKIP_NVM` or `HUSKY_SKIP_NVM_USE` if you are willing to merge it?

**Comment by typicode** [comment]
Hi @screendriver ,

The next release probably won't use `nvm` directly.

There's a beta if you want to give a try:
https://github.com/typicode/husky/tree/dev

It's still a beta though, so if you need something stable you should stay on `0.14`.

**Comment by screendriver** [comment]
Cool, thank you :+1:

**Comment by yadomi** [comment]
Any update on this ? 

As far as I understand [here](https://github.com/typicode/husky/blob/5e27cf888d5b0cebf5bb6bd9b1c2fb54911eb62b/src/utils/get-hook-script.js#L9), if husky is installed on non win32 platform, there is no way to disable nvm ? 

This mean even if you don't use nvm, nvm will be load only because it's installed on the system. NVM is really slow to load and it's annoying when a commit-msg hook is defined.

**Comment by rainboxx** [comment]
@yadomi according to the code, `nvm` should not run on win32 platforms at all.

However, the `dev` branch at https://github.com/typicode/husky/tree/dev has `nvm` functionality removed completely.

**Comment by typicode** [comment]
I confirm what @rainboxx said.

If you're not using `nvm`, husky won't load it. Husky can work without it, it will simply rely on the `node` command that is in the `PATH`.

And if you're on Windows, it will never try to use `nvm` because there's simply no Windows version of `nvm` :)

Also as @rainboxx mentioned, `v0.15` removes `nvm` functionality ;)
