### ISSUE TITLE
{*,**/*} doesn't work

### ISSUE THREAD

**Issue by corysimmons** [typicode/husky#187]
Use case: Auto-toc'ing all my `.md` files via https://github.com/jonschlinkert/markdown-toc

Attempted:

`"precommit": "markdown-toc -i {*,**/*}.md"`

Works if I just `node_modules/.bin/markdown-toc -i {*,**/*}.md`, but craps bed on commit. I'm assuming Husky isn't able to do wildcards?

**Comment by abustamam** [comment]
Did you try running `npm run precommit`?

**Comment by typicode** [comment]
Hi @corysimmons,

Not a 100% sure, but It may be related to the the shell it's running in. If `markdown-toc` supports it, you could try adding `'` around the glob pattern:

```
"markdown-toc -i '{*,**/*}.md'"
```

For example, [tape](https://github.com/substack/tape) and [prettier](https://github.com/prettier/prettier) add quotes in their examples so that they can do the expansion rather than the shell.

In any case, husky is neutral and doesn't perform any action to enable or disable this pattern.
