### ISSUE TITLE
Why skipping "hook adding" is CI is present?

### ISSUE THREAD

**Issue by dragGH102** [typicode/husky#189]
CI is great and can make many checks.
However, why skipping the pre-commit (e.g. eslint) entirely and delegating the CI the failure? (unless I'm missing the point of the code @ bin/ here)

**Comment by typicode** [comment]
Hi @dragGH102,

It's because most of the time CIs don't use Git commands that would trigger Git hooks. So there are no particular reasons for installing hooks, plus it may cause some side effects.

For example, Travis clones the repo and runs the commands in [.travis.yml](https://github.com/typicode/husky/blob/master/.travis.yml) but won't `git commit` anything.

Husky is mainly a developer tool to be installed locally. No worries, if Husky doesn't install Git Hooks in CIs, it doesn't prevent them from running tests, linters, etc...

That said, let me know if you're in a case where you would need them to be installed. I'm always interested in better understanding use cases :)
