### ISSUE TITLE
pre-push only in x branch?

### ISSUE THREAD

**Issue by vanor89** [typicode/husky#200]
Hey guys, title says it all pretty much, was just wondering if there was a way of running a script on pre-push but only for the `x` branch, if its `y` branch run this other script.

**Comment by DaddyWarbucks** [comment]
I would really love support for this too. I used a package called git-validate that supported this: https://github.com/nlf/git-validate
Git validate has a different use case and different implementation. Because there are actual `installHook` and `configureHook` methods with configure the git hooks dynamically, this may not be possible in husky.
But the syntax of `"pre-commit#dev": ["lint"]` is really nice.

**Comment by sreichi** [comment]
You can also run powershell scripts there if you are on windows.
`powershell if((git symbolic-ref --short HEAD).Contains('feature') -or (git symbolic-ref --short HEAD).Contains('bugfix') -or (git symbolic-ref --short HEAD).Contains('hotfix')-or (git symbolic-ref --short HEAD).Contains('develop')){npm run ...;}"`
This worked very well for me

**Comment by alexeyMohnatkin** [comment]
is there crossplatform soultion?

**Comment by Mr-Eluzive** [comment]
I think this can be helpfull. 
https://github.com/typicode/husky/issues/186

**Comment by philals** [comment]
Not sure if this package support it out of the box but you could do something like this:

```
#!/usr/bin/env bash

BRANCH=`git rev-parse --abbrev-ref HEAD`

if [[ "$BRANCH" == "master" ]]; then
  echo "You are on branch $BRANCH. "
  exit 1
fi

exit 0
```
