### ISSUE TITLE
Husky performs file staging (git add) too late

### ISSUE THREAD

**Issue by MartinMuzatko** [typicode/husky#213]
Hello there! I'm using husky to update an SQL schema that should be added via `git add` on `pre-commit`

```js
  "scripts": {
    "precommit": "server/scripts/export-sql-schema.sh; git add data/db/sicon.schema.sql"
  },
```

It looks like the file only gets added to git after the commit hook is run.
What am I doing wrong?
![commithook](https://user-images.githubusercontent.com/2950505/33278908-33113a90-d39d-11e7-84a2-eb93b886dcee.gif)

**Comment by Asuza** [comment]
I too want to know how to get this to work.

**Comment by motss** [comment]
@MartinMuzatko @Asuza 
With your solution, I managed to achieve what I wanted to. Almost all my projects need to load `.env` files and I'm looking for ways to auto-generate `.env-sample` files whenever I commit something. `"precommit": "npm run env; git add .env-sample"` is what I have been looking for! 👍

**Comment by MartinMuzatko** [comment]
Does that work for you @motss ? 
In my case, `git add` is only executed after the commit, as it looks like.

**Comment by motss** [comment]
`git add` does work.

Based on what I see, I think the command will run before commit which is why it's called `precommit`. Then before committing the git message, we need to `git add` any files that have been changed during the `precommit`. If not doing that, the message will be committed to `git` and any files that receive changes during the `precommit` will be staged.

**Comment by j-martyn** [comment]
What happens here is that when you trying to make a commit with empty index then git won't do it unless you provide `--allow-empty` option to it.
Nevertheless, it runs pre-commit hook, but files added during its execution are not being counted for commit emptiness checking because it has been already done once.
If you will have some files added to the index or will pass `--allow-empty` option everything will work as expected.

I believe this issue can be closed.

**Comment by FDiskas** [comment]
You can reopen this `husky@2.4.1` :traffic_light:
```
git commit --quiet --allow-empty-message --file -
Info: can't find node in PATH, trying to find a node binary on your system
husky > pre-commit (node v10.16.0)
Current directory is not a git directory!
husky > pre-commit hook failed (add --no-verify to bypass)
```

**Comment by apgapg** [comment]
For me this worked, otherwise it won't include formatted file after `npm run lint`
```
  "husky": {
    "hooks": {
      "pre-commit": "npm run lint; git add ."
    }
  }
```

**Comment by dwjohnston** [comment]
> For me this worked, otherwise it won't include formatted file after `npm run lint`
> 
> ```
>   "husky": {
>     "hooks": {
>       "pre-commit": "npm run lint; git add ."
>     }
>   }
> ```

The problem with this solution is that it will add everything to the commit. If you have change three files but are only trying to commit one of then adding `git add .` will erroneously commit everything.
