### ISSUE TITLE
cd dist in pre-commit 

### ISSUE THREAD

**Issue by Alexis-benoist** [typicode/husky#232]
We have some people in the team who have in the line 12 of the pre-commit script a `cd "dist"` while some others don't have it.

Why is that?

How to disable it to only run the hook at "."?

**Comment by typicode** [comment]
Hi @Alexis-benoist,

`cd "some/path"` is the relative path from your project directory to the directory containing `package.json`.
For example, if you have this structure directory

```sh
project/.git
project/sub-project/package.json # contains husky devDependency
```

Then installing husky in B will result in this:

```sh
project/sub-project$ npm install
project$ cat .git/hooks/pre-commit
# ...
cd "sub-project"
# ...
```

If you have multiple `package.json` containing there may be one that overwrites the others

```
project/package.json # contains husky devDependency
project/sub-project/package.json # contains husky devDependency as well
```

```sh
project/sub-project$ npm install
project$ npm install
project$ cat .git/hooks/pre-commit
# ...
cd "." # because `npm install` from project was the last to run
# ...
```

Besides that, I'm not sure why you would have such a difference. Do you have multiple `package.json`?
Re-running `npm install` should overwrite previously installed Git hooks.

Another reason could be if you had a `dist` directory and moved its content to the root of your project, but I doubt since re-running `npm install` would have fixed the issue.

**Comment by typicode** [comment]
`v0.15.0` which is available under `@next` (currently a `release candidate`) approaches sub-projects differently, if you want to give it a try:

README https://github.com/typicode/husky/tree/dev 
Docs https://github.com/typicode/husky/blob/dev/docs.md
