### ISSUE TITLE
missing something with prepush hook

### ISSUE THREAD

**Issue by tomdavidson** [typicode/husky#248]
This is most like a git thing rather than a husky thing but huskey is the use case so I amhoping to get further direction. I have the following script invoked on a prepush hook with huskey:

```sh
npx pandoc \
  --toc --toc-depth=1 \
  --template=other/README.md.template \
  -o README.md \
  -B _README.md \
  data/*.md

git add README.md

git commit --amend --no-edit
```

Everytime the push is rejected until I merge with git pull, but I am in my own branch, there are no other contribs. The merge shows no changes.

```shell
error: failed to push some refs to 'git@gitlab.com:org-name/devops/runbooks.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
```

**Comment by weslexcore** [comment]
This means that your remote branch (what you have already pushed) is ahead (has some commits that you do not have locally).

If you want to take what you have locally and overwrite the remote you can pass the `-f` flag to force the push but fair warning - there is no retrieving your information after a force push so be sure that you  want your local to overwrite.

Otherwise, do a `git pull <remotename> <branchname>` to pull the changes that are in your remote into your local. You may have to fix some merge issues and then you should be able to push.

**Comment by tomdavidson** [comment]
Hello @weslexcore right, but what is confusing is that the remote is not adhead. The only push to the branch is me with husky. No one else is on the branch. Doing a pull first creates a merge commit  of nothing for every time I want to push.

What I had to do is just add the build task to my precommit hook and get rid of the prepush hook - which is slow and fairly annoying.

Im sure this is user error, but it is not so obvious.

**Comment by alanbsmith** [comment]
It might be that when you `amend`, you create a new sha1 for the commit (even if you aren't editing the message). Git is saying, "Hey, what you have locally doesn't match what's pushed up on that branch." @weslexcore is correct that you would need to force push or add a new commit on top and then push.
