### ISSUE TITLE
Option to allow package.json to be at a different level that .git

### ISSUE THREAD

**Issue by pzuraq** [typicode/husky#272]
In the 1.0.0-rc.1 release it's currently not allowed at all to have a node project nested in a folder within a git project:

```
Expecting package.json to be at the same level as .git, skipping Git hooks installation.
```

Due to historical reasons, ours is nested just one folder in and the repo doesn't contain any other projects. This will likely change in the future, but it's a matter of getting there, and we'd like to use husky in the meantime 😄Any chance we can add an option to allow this?

**Comment by malixsys** [comment]
They should use `git rev-parse --show-toplevel`  from a child process to find the git root...

**Comment by typicode** [comment]
Hi @pzuraq, @malixsys,

Technically it's not that complicated, `husky v0.14` was looking for `.git`, even if `package.json` wasn't at the same level.

The downside of this was that it was possible to define `husky` in multiple `package.json`:

```sh
.git
foo/package.json # with husky
bar/package.json # with husky
```

There could be different versions of husky, `bar` could overwrite hooks installed by `foo`, ...

Enforcing a `package.json` at the same level as `.git` makes sure that you have just one version of `husky`, i.e. one source of truth.

@pzuraq If your project is in a subdirectory, there's a workaround though :
https://github.com/typicode/husky/blob/dev/docs.md#sub-directory-package

But I don't know if it would fit your project?

That said, I'm thinking about re-introducing the `0.14` behaviour since it seems many projects have this constraint.

**Comment by pzuraq** [comment]
I think it would make sense to have the `0.14` behavior be toggleable, I agree that it's not the best for _all_ projects, but I do think it makes sense for our use case. We just can't introduce that top level `package.json` at the moment, it'll happen but it's not really possible right now.

**Comment by joeytwiddle** [comment]
In our repository we do host multiple projects (each with its own package.json file). I added husky to both of them.

But looking in `.git/hooks/pre-commit` I see that husky runs _only_ against the _most recent_ sub-project/package.json where it was installed.

Since husky doesn't know which sub-project has been changed, I really want to run the linters for _all_ sub-projects when someone commits.

That was easy enough to achieve for two sub-projects. I put this same config in both `package.json`s:

```
  "lint": "eslint src && stylelint src",
  "precommit": "cd ../project1 && npm run lint && cd ../project2 && npm run lint",
```

Although I can see this approach might get tiring after you add your 6th sub-project! By that stage, you might want to use a tool like [lerna](https://www.npmjs.com/package/lerna).

**Comment by conatus** [comment]
Hey @typicode - above you allude to a workaround but the link is broken. How do you approach this?

Thanks.

**Comment by kas** [comment]
Thanks @joeytwiddle, sharing my solution, which is similar, but spawns a child shell:
```
{
"husky": {
    "hooks": {
      "pre-commit": "npm run pre-commit"
    }
  },
  "scripts": {
    "pre-commit": "(cd subfolder-1 && npm run eslint) && (cd subfolder-2 && npm run eslint) && (cd subfolder-3 && npm run eslint)",
  },
}
```

Assuming each subfolder package has an eslint script.
