### ISSUE TITLE
[1.1.0]: HUSKY_SKIP_INSTALL=true doesn't skip install

### ISSUE THREAD

**Issue by N44PS** [typicode/husky#370]
Hello everyone,

I'm trying to build a docker image from a repository and I don't want husky to be installed.
I used the `HUSKY_SKIP_INSTALL` but it doesn't seem to work.

```dockerfile
FROM node:9 as builder

RUN mkdir /src
WORKDIR /src

COPY package*.json ./
RUN HUSKY_SKIP_INSTALL=true npm install
COPY . .

FROM node:9-alpine

WORKDIR /src

COPY package*.json ./
RUN npm install --production
COPY --from=builder /src /src/
COPY --from=builder /src/server.js /src/

EXPOSE 3000

CMD ["node", "server.js"]
```

On the logs we can see : 

```
Step 5/14 : RUN HUSKY_SKIP_INSTALL=true npm install
 ---> Running in ...

> husky@1.1.0 install /src/node_modules/husky
> node husky install

husky > setting up git hooks
Can't find .git, skipping Git hooks installation.
Please check that you're in a cloned repository or run 'git init' to create an empty Git repository and reinstall husky.
```

I don't know why, maybe the environment variable is not known to the container ?

Thank you for your help,

Florian

**Comment by typicode** [comment]
Hi @N44PS,

The message is confusing but it "works".

Before installing git hooks, husky checks the following:

1. Does `.git` exists? If not, skip installation
1. Is `HUSKY_SKIP_INSTALL` true? If yes, skip installation
1. etc...

In your case, you're getting `Can't find .git` message since it fails with the first check.

I'll publish a new version that will check things in this order:

1. Is `HUSKY_SKIP_INSTALL` true? if yes, skip installation
1. Does `.git` exists? if not skip installation
1. etc...

For the moment I'd suggest not worrying about the message, it should be fixed soon.

**Comment by N44PS** [comment]
Oh ok, I didn't see that the `.git` part was first in the process.
I guess the new order would be better indeed, thank you @typicode :)

Have a nice day !

**Comment by typicode** [comment]
Thanks you too :) (it should be good now in `1.1.1`)
