### ISSUE TITLE
Explicitly opt-in instead of opt-out

### ISSUE THREAD

**Issue by friederbluemle** [typicode/husky#468]
Currently, without disabling Husky explicitly using `HUSKY_SKIP_INSTALL`, it automatically integrates with the local Git system.

I do understand some people may find it helpful to have stuff run automatically whenever performing certain Git actions, and that's okay. However, I think in some cases it should be by choice rather than forced.

Why?

Here is an example:

I expect a Git commit to take in the order of 10s of **milliseconds** (_maybe_ a few hundred milliseconds if the commit is cryptographically signed). Not more than that. Here's the problem: Someone added a hook to "**run the linter, the formatter, and unit tests with every commit**". Now suddenly each commit can take **10s of seconds**! I rebase, rewrite, and amend commits _all the time_. Waiting this long for each commit is unacceptable. This is even more frustrating when you know that absolutely nothing was changed that would justify running these actions.

I tend to be very explicit and precise with which command I run, and am fully aware of what each command does:

- When I want to run unit tests, I run unit tests
- When I want to format the code, I format the code
- When I want to run the linter, I run the linter

There is absolutely **no need to forcibly bundle** all of these independent actions together. In addition, most of these things should either happen on CI already, or the IDE can be set up to do it (manually or automatically).

My point here is, people have different workflows and opinions. There should be a way to set Husky to **explicitly opt-in** rather than opt-in by default. Maybe something like `npm run setup-husky` (which could be documented in the project's `README.md` to describe what it does).

A related issue that I just found after finishing typing: #258

**Comment by zupaox** [comment]
I think it is used to prevent unclean codes been push to repository. I feel better to move it to `git push`.

**Comment by typicode** [comment]
Not really opt-in/opt-out but some progress. Husky `2.4.0` now lets you skip all hooks using an env variable:

```sh
HUSKY_SKIP_HOOKS=1
```

**Comment by droddy** [comment]
HUSKY_SKIP_HOOKS is not what I'm looking for either. I'm using Husky to make sure that I and my teammates to not circumvent commitizen during commits. In other projects you'll see people using `yarn commit` in order to get git hooks that utilize commitlint/prompt running but, anyone could easily circumvent those hooks by just using `git commit` instead. I'm not trying to 100% prevent anyone from circumventing my hooks (HUSKY_SKIP_HOOKS is fine where appropriate) but I'm trying to make it harder and, hopefully, make it easier to ensure conventional-commit syntax is used. So, when I installed Husky using the HUSKY_SKIP_INSTALL environment variable, that was great--it avoided adding all the hooks I don't want or need. But as soon as a teammate gets latest and runs yarn or npm, Husky gets the full install based on package.json and *-lock.json. My teammates are going to be more likely to buy into the hooks I'm using if they don't have to do extra steps that are not related to the actual project we're working on together. The way Husky install works now, I have to tell all of my teammates to either remove and then re-install Husky using the skip_install option this time.

**Comment by JaredReisinger** [comment]
I'm not sure that changing husky's behavior is the solution.  As the original issue states (emphasis _**added**_):

> Here's the problem: _**Someone added a hook**_ to "run the linter, the formatter, and unit tests with every commit". Now suddenly each commit can take 10s of seconds!

It's not _husky's_ fault that these operations now take 10s of seconds... you're _asking_ that husky intervene and take 10s of seconds.  True, "you" are not the "someone" that did this, but figuring out what the convention for your team should be is out-of-scope for husky.  This is really no different from setting up git hooks directly; you and your team need to decide what checks you want run for each git hook, taking into consideration how often those git commands are run and how time-consuming the hooks will be.  (And if you have tests run in your CI pipeline, you have a good case for arguing that putting those checks also into the commit hook is overkill.)

**Comment by mokus0** [comment]
I don't even know what husky IS, and I find git hooks magically installed in my repo.  I'm exceedingly unhappy about a 3rd-party I've never even heard of installing code to my project that runs stuff when I use git.   Please make this opt-in.

**Comment by JaredReisinger** [comment]
The _only_ thing that husky exists for is to provide "auto-installed" git hooks for a project.  There is _**zero**_ reason to have it installed in a project if you're not going to use it for that.  Further, the reason one uses it for hooks is _to ensure that certain hooks are in place_, so that specific processes are followed for things like commits, etc.  When a git hook is in-place, it's not opt-in either.  Really, putting it in place, much like installing husky, is the "opt in" step.

@mokus0 , you write "my hooks" and "my repo", but you have a teammate that chose to add it to "your" project.  The decision to use (or not use) husky is one that your _**team**_ should make... you either _all_ decide to use it, or you don't (and then your team removes it from the project).  Part of making this decision is weighing the cost of running those hooks vs. the benefit you get from it.

**Comment by friederbluemle** [comment]
> figuring out what the convention for your team should be is out-of-scope for husky.

Sure that is 100% true, but that's also not what the issue is about. The point is: _Automatically_ installing hooks and modifying the default behavior of an essential and core component such as the Git version control system could _potentially_ make sense in a closed source project with a small and limited number of people that all share the same workflow.

How do you define "team" when you we're talking about an open source project with hundreds or thousands of contributors? Or even within a company where teams work independently and do not necessarily share the same workflow?

> The only thing that husky exists for is to provide "auto-installed" git hooks for a project. There is zero reason to have it installed in a project if you're not going to use it for that.

Why would there be no benefit of an opt-in manual install? People have different workflows, and some might find it beneficial to have stuff run automatically with Git commands. Husky is still pretty good at defining those actions (compared to manually editing/renaming the shell scripts in `.git/hooks`), even if they're opt-in.

**Comment by JaredReisinger** [comment]
@friederbluemle, you've convinced me that there _are_ use-cases where using husky to define _possible_ hooks might make sense.  I'm still not convinced that this is the "80" side of the 80/20 case, though.  I honestly don't see how "open source team" vs. "closed source team" makes any difference at all.  The _size_ of the team does, but as I said, that's part of the calculation when you determine whether you want husky to be a part of the project or not.

I agree that people have different workflows and opinions, but the organizing core behind any project, open source or not, _**also**_ needs the option to define by-default, project-wide requirements.  Were I a core member of a hundred/thousand-contributor-strong project, I would probably recommend _against_ putting in a heavy commit-time hook for the very reasons you are taking issue with.  Catching these issues in something like a PR build is actually a better solution because a contributor _can't_ opt out of that if they want their PR to be considered.  I don't know what project you're contending with, but at the very least it feels like you should open an issue with _that project_ to restrict or limit the kinds of hooks that are used via husky by default.  If you're feeling the pain of excessively slow commits, you probably aren't the only one!

For what it's worth, I have a couple of open-source-but-mostly-just-me projects, and I _want_ husky hooks to kick in before anyone (including me!) writes a commit message or commits... but these are small projects, and the time impact is very low.  They (or I) can always opt-out or use a command like `git commit --no-verify`... but the hooks are very intentionally there to help ensure that a particular process is followed.

(For the record, I'm neither in charge of husky, nor a contributor... but I'm pretty passionate about having tools that help with process and improving developer experience.)

**Comment by Hypnosphi** [comment]
Here's how I make husky an opt-in:

```json
// package.json
{
  "scripts": {
    "install-git-hooks": "npm install husky --no-save"
  }
}
```

**Comment by typicode** [comment]
With husky 5 install is explicit, so it should make opt-in easier to do now. It's still possible to have auto-install though.
Thanks for the feedback :)
