### ISSUE TITLE
Remove unnecessary mapping

### ISSUE THREAD

**Issue by adius** [typicode/husky#48]
https://github.com/typicode/husky/blob/master/HOOKS.md

What is this mapping good for, except that it makes it harder to read? (especially `preparecommitmsg`)

**Comment by typicode** [comment]
The reason for this mapping was to be consistent with npm's hook syntax (`prepublish`, `preinstall`, ...), since git hooks are defined in the same place.

I wanted things to look like this:

```json
{
  "scripts": {
    "prepublish": "npm test",
    "precommit": "npm test",
    "prepush": "npm test"
  }
}
```

Instead of this:

```json
{
  "scripts": {
    "prepublish": "npm test",
    "pre-commit": "npm test",
    "pre-push": "npm test"
  }
}
```

But at the time, husky was only supporting `precommit` and `prepush` scripts. So there wasn't anything long like `preparecommitmsg`.

Maybe it's an unnecessary mapping.

**Comment by typicode** [comment]
Closing as next version of husky will use real hook names (`pre-commit`, `pre-push`, ...), thanks again for the feedback :)
