### ISSUE TITLE
Can't find Husky warning after uninstall

### ISSUE THREAD

**Issue by tommybernaciak** [typicode/husky#486]
I added Husky to my project and I added hooks. Then I changed my mind and husky was uninstalled and all hooks were deleted, but I am still getting a lot of these:
```
Can't find Husky, skipping post-checkout hook
You can reinstall it using 'npm install husky --save-dev' or delete this hook
```
How I should uninstall it properly, what is the process for that?

**Comment by amypellegrini** [comment]
@tommybernaciak I've fixed this by removing the `/hooks` directory within the `.git` folder (make sure you can see hidden folders to access it).

I don't think this is the actual "proper" way to do this, my take is that `husky` should be able to do that when uninstalled, but since it doesn't, this is the workaround.

More details here: https://stackoverflow.com/questions/52096430/how-to-remove-remote-git-hooks#52096854

**Comment by tommybernaciak** [comment]
@amypellegrini Thanks, your solution helped me to clear this warning.

**Comment by typicode** [comment]
Hi @tommybernaciak,

The proper way is to run `npm uninstall husky`. It should trigger husky's uninstaller and remove only hooks installed by husky.

If you don't have personal hooks in `.git/hooks`, removing it manually is another way too :)

**Comment by tommybernaciak** [comment]
So it means that `npm uninstall husky` does not work correctly and it should be deleted manually.

**Comment by toienMT** [comment]
I've deleted the .git/hooks file and ran `nom uninstall husky` and I'm still getting the error

**Comment by basickarl** [comment]
Still broken.

**Comment by ugobriasco** [comment]
Yep, sill  broken on my side as well: both uninstalling or deleting manually do not solve the problem. Any ideas?

**Comment by altaurog** [comment]
Presumably only one person on the team will `npm uninstall husky`.  Everyone else will have to clean up manually.
