### ISSUE TITLE
can not get --no-verify arguments from HUSKY_GIT_PARAMS

### ISSUE THREAD

**Issue by linhuiw** [typicode/husky#515]
can not get --no-verify arguments from HUSKY_GIT_PARAMS:

![image](https://user-images.githubusercontent.com/722603/60168780-04585880-9838-11e9-8242-fd573e53e43c.png)

**Comment by typicode** [comment]
I'm not sure that it's possible to know with Git that `--no-verify`  has been used.

**Comment by linhuiw** [comment]
if you know git pid, maybe can simply through grep the command line.
```bash
ps -o args= $PPID | grep -E -q ' --no-verify| -n | -n$'
```

**Comment by linhuiw** [comment]
so in this time, HUSKY_GIT_PARAMS did not contain all git params?

**Comment by typicode** [comment]
Actually, Git only passes 1 to 3 params to the `prepare-commit-msg` hook:
https://git-scm.com/docs/githooks#_prepare_commit_msg

They're all forwarded in `HUSKY_GIT_PARAMS`

It might be confusing because it's not the params that are used in `git commit`.

I'll give a try to `ps -o args= $PPID | grep -E -q ' --no-verify| -n | -n$` thanks but it has to work on Windows so not sure.
