### ISSUE TITLE
Why husky working path is wrong ?

### ISSUE THREAD

**Issue by chenxxzhe** [typicode/husky#582]
My OS is windows

when i commit, husky change the working path to '/' which is not my project path.

why?

I echo the working path in pre-commit hook:

![215411569400633_ pic_hd](https://user-images.githubusercontent.com/9720961/65585069-70239c00-dfb4-11e9-9fac-b24de02ee9db.jpg)

Because the working path changed, lint-staged can't find package.json, so it throw error: `no such file or directory, open "E:\package.json"`

**Comment by chenxxzhe** [comment]
husky version v3.0.5

**Comment by fishenal** [comment]
My peer has the same issue, also on v3.0.5, but my project run properlly

**Comment by typicode** [comment]
Could you try re-installing with `HUSKY_DEBUG=1`? I've also added some additional debug messages in `v3.0.7`.

And `HUSKY_DEBUG=1 git commit ...` should provide some information too.

**Comment by fishenal** [comment]
> My peer has the same issue, also on v3.0.5, but my project run properlly

Well, my peer's issue is, he set windows system cmd default root, seems like this confuse husky to find the right root path.  try to remove the sets like this.

**Comment by chenxxzhe** [comment]
@typicode 
![WechatIMG22610](https://user-images.githubusercontent.com/9720961/66557150-fbd82380-eb83-11e9-912f-f2dbd2142b15.png)
![WechatIMG22651](https://user-images.githubusercontent.com/9720961/66557153-fe3a7d80-eb83-11e9-8cad-5665e10b121e.png)

**Comment by typicode** [comment]
Could you retry with husky `4.0.0-beta.5`?

**Comment by chenxxzhe** [comment]
> Could you retry with husky `4.0.0-beta.5`?

resolved!!! thank you very much!!

**Comment by adamchew89** [comment]
Hi, I have a similiar issue where Husky seems to be working from the wrong directory:

![image](https://user-images.githubusercontent.com/20580947/68458335-83758880-023d-11ea-86e7-687bc2bfe02c.png)

I had to censor some information but generally:

I have a CRA project in: `C:\Users\<user>\Desktop\projects\repository\<directory with spacing in name>\<project root directory with spacing in name where node_modules are found>

But when running ```HUSKY_DEBUG=1 git commit -m "test"```, I get the above screenshot where it is trying to execute the run.js from the parent folder `C:\Users\<user>\Desktop\projects\repository\`.

I am already trying 4.0.0-beta.5.

Using 3.0.9 runs husky but fails when it tries to execute the command 'lint-staged' as it fails to find import from the wrong path:  `C:\Users\<user>\Desktop\projects\repository\lint-staged\...`.

Not too sure if the issue is with husky.

**Comment by adamchew89** [comment]
The problems seems to be due to the special characters in my path. '&' seems to be the guilty one.

**Comment by alexjameslowe** [comment]
`vi .git/hooks/husky.local.sh` and see if it does something like `cd "src/some/wrong/folder/"`. Delete that line and run `HUSKY_DEBUG=1 git commit -a -m "Testing 1 2 3"` and it should work and also read out the current working directory that husky is using.
