### ISSUE TITLE
how to disable specific hooks？

### ISSUE THREAD

**Issue by WilkinWendy** [typicode/husky#602]
In my project,I only want to proxy the pre-commit hook to help me lint code,but I found all hooks were proxied ,can I disable others or cancel the rewriting of other hooks

**Comment by typicode** [comment]
Hi @WilkinWendy,

One way to do it would be to create empty hooks. Since husky never overwrites existing user hooks, that would disable them.

That said, the overhead with all hooks proxied is minimal:
- less than half a second usually
- just a couple hooks are run for each commands (can be seen with `HUSKY_DEBUG=1`)

The benefit is that hooks can be added later without having to re-run husky installation.

**Comment by WilkinWendy** [comment]
> Hi @WilkinWendy,
> 
> One way to do it would be to create empty hooks. Since husky never overwrites existing user hooks, that would disable them.
> 
> That said, the overhead with all hooks proxied is minimal:
> 
> * less than half a second usually
> * just a couple hooks are run for each commands (can be seen with `HUSKY_DEBUG=1`)
> 
> The benefit is that hooks can be added later without having to re-run husky installation.

yeah I understand your consideratoin. But I still consist of the future feature of  custom rewriting of hooks,
for me , the commit will takes about 10 seconds, which make me crazy..

**Comment by typicode** [comment]
Closing to clean up the issues list but I'm keeping it in mind. Thanks for the feedback :+1:
