### ISSUE TITLE
.rej files

### ISSUE THREAD

**Issue by GlauberF** [typicode/husky#610]
In some cases, which I haven't figured out yet, when running hooks, it creates a .rej file.
And I'm sure it's something with the library or the other that we use lint-staged.
Because before implementing this, you never created these files

package:
```
"husky": {
        "hooks": {
            "pre-commit": "ng lint --fix && lint-staged"
        }
    }
```

my config
```
{
    "**/*.{ts,js,json,css,scss}": [
        "./node_modules/.bin/prettier '**/*.{ts,js,json,css,scss}' '.prettierignore*/{__name__,__directory__}/**' --write",
        "git add"
    ]
}
```

**Comment by typicode** [comment]
`.rej` seem to be Git related files. I can confirm though that there's nothing in husky code that creates explicitly `.rej` files.

**Comment by kirillgroshkov** [comment]
I have the same issue. Suspecting some kind of race condition between husky and the scripts that it runs pre-commit. Because we I run pre-commit scripts separately from husky - they finish correctly. When I run with husky - they sometimes create `.rej` files and sometimes just don't save what pre-commit scripts saved (prettier, in my case).

Reverting to `3.x` fixed it for me.
