### ISSUE TITLE
Git: husky > pre-commit (node 12.9.1)

### ISSUE THREAD

**Issue by todd-h-davis** [typicode/husky#686]
I just started to get this message today when checking in my code to Github. As far as I know, Husky works with NodeJS 12.9.1, right? I see no other error messages. This is happening when using VSCode to check in code. All versions of Husky/NPM/NodeJS/VSCode are all latest versions. 

Any thoughts as to what Husky is trying to tell me? (I am a complete noob to Husky)

**Comment by typicode** [comment]
All hooks start with this message. It's the beginning of husky output.

Node version is displayed because with GUI you may sometime get a different Node version than the one in your terminal. So to avoid confusion, Node version is explicit and always displayed.

In any case, nothing to worry about this message, it's normal ;)
