### ISSUE TITLE
how to get git params

### ISSUE THREAD

**Issue by Leslie2014** [typicode/husky#71]
hi.
i want to prevent git push when branch name match the regular expression.
so, the question is, how can i get the command cli param. 
e.g: git push publish/0.0.4, the string 'publish/0.0.4' is what is want.

**Comment by typicode** [comment]
hi @Leslie2014,

Git params are passed in `GIT_PARAMS`:

```json
"prepush": "node prepush.js"
```

```js
// prepush.js
console.log(process.env.GIT_PARAMS)
```

I'll update the README :)

**Comment by Leslie2014** [comment]
Thanks!  : )

**Comment by hungHoangDang** [comment]
Hi @typicode , I know this issue is closed but I ran into this same situation and it doesn't work like your answer. I also try https://github.com/typicode/husky/issues/113#issuecomment-407338401 but to no avail. Of course I knew that `prepush` is now `pre-push` but still. If I use HUSK_GIT_PARAMS then I only receive the **url for repo** but not the branch name. Is there a way to work around this? Many thanks!

**Comment by shiftgeist** [comment]
I have the same issue as @ghun131 and didn't find any workaround yet.
