### ISSUE TITLE
Skip Husky pre-commit on merge commits

### ISSUE THREAD

**Issue by HarryBurns** [typicode/husky#751]
I'd like to configure somehow Husky to skip scripts associated with the "pre-commit" hook on merge commits. Maybe something like
`{
  "husky": {
    "hooks": {
      "pre-commit-except-merge": "my script",
    }
  }
}`

Usecases: do not run prettier or linter from Husky "pre-commit" hook on merge commits.

**Comment by typicode** [comment]
Haven't tested but this seems to do the trick
https://stackoverflow.com/a/27800562

**Comment by spyro2000** [comment]
The workaround is a little bit hacky and doesn't work on non-Linux systems

**Comment by maxevilmind** [comment]
A lot of people actually need this functionality, especially when working in monorepo with multiple eslint configurations. There needs to be support on husky level instead of silly workarounds.

**Comment by SeongwoonHong** [comment]
any info on when this will be added as a feature?

**Comment by Squixx** [comment]
Please dont close this... 

Would love something here that works x-platform

**Comment by Yohandah** [comment]
interested as well

**Comment by zhe1ka** [comment]
+1

**Comment by zorzysty** [comment]
Would love to have this feature as well. Can it be re-opened?

**Comment by twoKilo** [comment]
+1 it would be really nice to have this feature

**Comment by danielglobant** [comment]
+1

**Comment by ihrynkiv** [comment]
+1

**Comment by romanzhivo** [comment]
+1

**Comment by gn-spawn** [comment]
+1

**Comment by fatso83** [comment]
Instead of +1's, just put in the work and supply a PR. This is obviously not moving anywhere. If you want an external solution, just stuff this in your Husky config:

```
"pre-commit": "is-rebase-or-merge || do-something"
```

and do `npm install @fatso83/is-rebase-or-merge`. That does a traversal in the file system that should work pretty much OS independant. That util can also be called as a Node module, if anyone should bother integrating it. And accepting PRs, ofc.

**Comment by joelkesler** [comment]
Thanks @fatso83!

In order to speed up our pre-commit hook, I took your `is-rebase-or-merge` project and reimplemented it in bash.

So now my `.husky/pre-commit` file looks like this:

```bash
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Set the git root folder path
GIT_ROOT=$(git rev-parse --show-toplevel)

# Define the rebase and merge paths
REBASE_PATH="$GIT_ROOT/.git/rebase-merge"
MERGE_PATH="$GIT_ROOT/.git/MERGE_HEAD"

# Check if the rebase or merge path exists.
# If they don't, it's a normal commit and we can run the pre-commit hook
if [ -f "$REBASE_PATH" ] || [ -f "$MERGE_PATH" ]; then
  echo "Skipping Husky pre-commit hook: We are in the middle of a rebase or merge."
else
  echo "Running Husky pre-commit hook: Formatting affected files"
  npx pretty-quick --staged
fi
```

**Comment by fatso83** [comment]
@joelkesler Nice. Just a FYI, I think that different (later) Husky versions (might) break this due to relying on different assumptions. Don't remember the specifics, as I stopped using Husky in newer projects after it turned into this complex monster that did not resemble its humle beginnings 😄 

The same tests can also easily be extended to cover cherry-pickings and other in-progress operations that will stumble upon the same issues.

**Comment by d0ragon** [comment]
Hey @joelkesler, thank you for your comment, it guided me in the right direction. Came here to say that apparently the rebase-merge path is a directory and not a file, so the check should be `-d` instead of `-f`. Plus, we can get the rebase and the merge paths directly with `git rev-parse git-path ...`, so here's a modified version of your script:
```shell
#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

# Define the rebase and merge paths
REBASE_PATH="$(git rev-parse --git-path rebase-merge)"      # directory
MERGE_PATH="$(git rev-parse --git-path MERGE_HEAD)"         # file

# Check if the rebase or merge path exists.
# If they don't, it's a normal commit and we can run the pre-commit hook
if [ -d "$REBASE_PATH" ] || [ -f "$MERGE_PATH" ]; then
  echo "Skipping Husky pre-commit hook: We are in the middle of a rebase or merge."
else
  echo "Running Husky pre-commit hook: Formatting affected files"
  npx nx format:write --uncommitted
fi

```
