### ISSUE TITLE
Husky uses different node / npm version to execute precommit hook

### ISSUE THREAD

**Issue by michaelBenin** [typicode/husky#77]
Currently I'm using different node versions for different projects.

Husky is currently using a different version of node and npm to execute the precommit hook instead of the one that is currently used for nvm. 

Is this expected behavior?

**Comment by typicode** [comment]
Hi @michaelBenin,

If Node version is changed without setting it as the default, yes husky will still use the default one.

```sh
nvm alias default 6
nvm use 5
git commit -m '...' # will use 6
```

To fix this, you can either set a new default or create a `.npmrc` file in your project directory:

```sh
echo 5 > .npmrc
git commit -m '...' # should use 5
```

Maybe this can be improved.

**Comment by michaelBenin** [comment]
Why does husky care if I use nvm or what my default is? Why would it use that instead of the current version of node? I've switched to https://www.npmjs.com/package/pre-commit which uses current node version. Feel free to reopen this issue.

**Comment by Moeriki** [comment]
I too would prefer husky to use my current node instead of the default.

Is there a technical issue that would prevent this change, and would you accept a pull request to resolve this?

**Comment by mkimberlin-monsanto** [comment]
Agreed. This should really be reopened.

**Comment by typicode** [comment]
Hi all,

This has been updated and solved in `v0.12`, sorry for the confusion. The current behaviour is: if you already have Node in your `PATH` it should use it without trying to load some other version.

So why does husky care about `nvm`? It's actually for the many users that use GUI apps (like SourceTree, GitHub client, etc...).

Since `nvm` changes `PATH` only in the terminal, apps will fail to find Node and won't be able to run hooks. That's why husky looks for Node and loads `nvm` version, to be able to run hooks in GUI apps context.

**Comment by mkimberlin-monsanto** [comment]
We ran into this with 0.12.0.

**Comment by typicode** [comment]
Ok that's a bug then, thanks for the report :+1: I'll double check

**Comment by typicode** [comment]
hi @mkimberlin-monsanto,

I suspect that your issue happens when Node is installed using `nvm` and `nvm` installed using `brew`. Is this how Node is installed on your machine?

**Comment by rainboxx** [comment]
@typicode Hey, I ran into something like this today as well since the system's (macOS) default version is not capable of features I started to use. Looking into the hook I found out that husky only uses `nvm` if there's no `npm` in the path. Since macOS has node installed as default (or, at least on my machine, it's installed plus `nvm`), husky will never pick up my `.npmrc` in the project root. Maybe this is related to what people were experiencing here?

Additionally I also seem to be running into this issue: https://github.com/typicode/husky/pull/100

I added a PR for this, would be awesome if you can take a look: https://github.com/typicode/husky/pull/101

**Comment by jedwards1211** [comment]
@typicode I don't get it, if `husky` is run in a context where `node` isn't on the `PATH`, shouldn't it just fail?  Isn't it the user's responsibility to make sure `node` is on the `PATH` for `husky`?

**Comment by awilkins** [comment]
Also running into this when using `ndenv` ... and the .node-version is 6.11.3 ... and the default system node is 6.11.2 ... and husky is still picking 4.5.0, because I *used* to use `nvm` and had it's folder hanging around and there's a copy of 4.5.0 in there.

This is failing from the command line.. with the `node` on my PATH being the ndenv shim.

Remove the `.nvm` folder and it all works as the digital gods intended - it uses the `node` on my PATH, which is the `ndenv` shim, which selects the node I want.

**Comment by matewilk** [comment]
@typicode comment helped me, but even though I'm on `husky` version `0.14.3` it still uses a default `mvn` node version. In my case the default is `6.11.2` but I use `8.7.0` and `husky` still uses the `6.11.2` version.

Just saying!

**Comment by chenqiuxia** [comment]
@matewilk 
[stackoverflow](https://stackoverflow.com/questions/43932038/husky-giving-error-syntaxerror-use-of-const-in-strict-mode)
I had same problem today and solved by this link.
I just deleted my $HOME/.nvm folder and everything worked fine

**Comment by jedwards1211** [comment]
@typicode 
> The current behaviour is: if you already have Node in your PATH it should use it without trying to load some other version.

Is this no longer the case?  The hook script it gave me doesn't check for `node` on path at all, it just loads `nvm` regardless.

```sh
!/bin/sh
#husky 0.14.3

command_exists () {
  command -v "$1" >/dev/null 2>&1
}

has_hook_script () {
  [ -f package.json ] && cat package.json | grep -q "\"$1\"[[:space:]]*:"
}

cd "."

# Check if precommit script is defined, skip if not
has_hook_script precommit || exit 0

load_nvm () {
  # If nvm is not loaded, load it
  command_exists nvm || {
    export NVM_DIR=/Users/andy/.nvm
    [ -s "$1/nvm.sh" ] && . "$1/nvm.sh"
  }

  # If nvm has been loaded correctly, use project .nvmrc
  command_exists nvm && [ -f .nvmrc ] && nvm use
}


# Add common path where Node can be found
# Brew standard installation path /usr/local/bin
# Node standard installation path /usr/local
export PATH="$PATH:/usr/local/bin:/usr/local"

# nvm path with standard installation
load_nvm /Users/andy/.nvm

# nvm path installed with Brew
load_nvm /usr/local/opt/nvm
```

**Comment by jedwards1211** [comment]
@typicode and it calls `load_nvm` twice even if the first call succeeds, wasting extra time.

**Comment by RayBenefield** [comment]
Just echoing as I ran into this today. Ran my tests manually fine and noticed my updated `precommit` hook was failing because it was missing `util.promisify`. Threw me off like crazy.

**Comment by jedwards1211** [comment]
Everyone please upvote my PR: #214

**Comment by rdsedmundo** [comment]
I'm running in the same problem, and as pointed above already, for me it also doesn't make sense. A package shouldn't care about NVM or whatever I'm using for managing my Node version, it should simply use the current Node version that the `node --version` command outputs.

**Comment by avalonabecker** [comment]
I'm running into the same problem:
ERROR: Upgrade husky. husky > pre-commit (node v6.9.5) undefined requires at least version 8.6.0 of Node, please upgrade husky > pre-commit hook failed (add --no-verify to bypass)
```
         v6.0.0
         v6.7.0
         v6.9.5
        v6.11.2
         v7.5.0
         v7.9.0
         v8.0.0
        v8.11.3
->      v10.8.0
       v10.12.0
default -> 10.8.0 (-> v10.8.0)
node -> stable (-> v10.12.0) (default)
stable -> 10.12 (-> v10.12.0) (default)
```
ENV:
MANPATH=/Users/$myusername/.nvm/versions/node/v10.8.0/share/man:/usr/share/man:/usr/local/share/man:/opt/X11/share/man:/Library/Developer/CommandLineTools/usr/share/man
NVM_CD_FLAGS=
NVM_DIR=/Users/$myusername/.nvm
NVM_BIN=/Users/$myusername/.nvm/versions/node/v10.8.0/bin
NVM_IOJS_ORG_MIRROR=https://iojs.org/dist

package.json
"husky": "^1.3.1",
"lint-staged": "^8.1.0",

I tried `rm -rf node_modules package-lock.json && npm i` but still getting the same error above.
Does anyone have suggestions on how to fix?

**Comment by lokers** [comment]
`nvm alias stable default`

**Comment by derekwsgray** [comment]
This should be reopened. It's still a problem.

**Comment by bobrosoft** [comment]
If you're using macOS and NVM, then that's the proper solution: just create `.huskyrc` in your `~` home directory with next content:
```
#!/usr/bin/env bash

source ~/.bash_profile

if test -f ".nvmrc"; then
    nvm use
fi
```
NOTE: it using your .bash_profile where NVM initialization should be already defined earlier when you installed NVM. I.e. next
```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
```

**Comment by slashwhatever** [comment]
> actually for the many users that use GUI apps (like SourceTree, GitHub client, etc...).

I'm having this issue **only** in GUI's like GitKraken and Sublime Merge

**Comment by simeonpashley** [comment]
Using Ubuntu + GitKraken, local `.nvmrc` was being ignored until I added the previously mentioned code specifically in `~/.huskyrc`. It wont work from your project directory, it has to be in your home directory.

```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
```

**Comment by simeonpashley** [comment]
This also fixes Ubuntu/Linux. I had this issue when using GitKraken husky precommit hooks.

> If you're using macOS and NVM, then that's the proper solution: just create `.huskyrc` in your `~` home directory with next content:
> 
> ```
> #!/usr/bin/env bash
> 
> source ~/.bash_profile
> 
> if test -f ".nvmrc"; then
>     nvm use
> fi
> ```
> 
> NOTE: it using your .bash_profile where NVM initialization should be already defined earlier when you installed NVM. I.e. next
> 
> ```
> export NVM_DIR="$HOME/.nvm"
> [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
> ```

**Comment by sainthkh** [comment]
In my case, the cause of the problem was the system nodejs. I removed it with `sudo apt remove nodejs` and set `nvm alias default 12.18.0`. 

It's all clear!

**Comment by lordlycastle** [comment]
Okay. This is silly. It should case if you use `nvm` because that is tool that will change behaviour. If people use `nvm` then they usually have `.nvmrc` file in their project so it should call `nvm use` not `nvm use default` because default will be whatever and it had nothing to do with the project.

Regarding using whatever node happens to be loaded at time argument. This defeats the purpose of `nvm`, now you'll somehow have to call `nvm use` yourself in all husky scripts.

Are we every going to get fix for it to use modules node version? What is the current solution today? Is it use `~/.huskyrc`?

**Comment by jedwards1211** [comment]
Are you sure most people will have .nvmrc in the project?  I've never used it and can't remember seeing .nvmrc in any OSS repos

**Comment by arvinsim** [comment]
Is there any resolution to this? I am still having the same problem.

**Comment by arvinsim** [comment]
> Are you sure most people will have .nvmrc in the project? I've never used it and can't remember seeing .nvmrc in any OSS repos, it doesn't seem on the same level with a babel config file for example

Maybe not most people. But you can't assume that people will use the same node version for all their node/javascript projects in one machine.

**Comment by hyoretsu** [comment]
I have tried all of the above, and my $NVM_DIR does correctly point to ~/.nvm, but I still get "could not determine executable to run".

.huskyrc
```
#!/usr/bin/env bash

source ~/.zshrc

if test -f ".nvmrc"; then
    nvm use
fi
```
.zshrc
```
### Added by NVM Installer
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
### End of NVM Installer section
```
Already tried the part in [FAQ](https://typicode.github.io/husky/#/?id=command-not-found) in both .huskyrc and .zshrc, none worked.

**Comment by BuistvoPloti** [comment]
If you are using nvm and faced this issue, you need to set a default node version via nvm (so it would match the one you are using)

**Comment by tvanantwerp** [comment]
A word of warning for anyone who tries the following with oh-my-zsh:

```sh
#!/usr/bin/env bash

source ~/.zshrc

if test -f ".nvmrc"; then
    nvm use
fi
```

This is a _bash_ script, not a _zsh_ script. By sourcing `.zshrc`, you're calling oh-my-zsh inside of bash rather than zsh as intended. [This will give you problems.](https://github.com/ohmyzsh/ohmyzsh/issues/10213) Better to just duplicate adding nvm to your path in `.bash_profile` than try invoking `.zshrc`.
