### ISSUE TITLE
Unstable pre-commit/pre-push hooks work

### ISSUE THREAD

**Issue by Eljoy** [typicode/husky#775]
Pre-commit, pre-push hooks work unstable. Pure frustrations. Sometimes they do work, but every now and then they just don't. After npm rebuild they start working again.
 My setup:
version:   "husky": "^4.3.0",
```

  "husky": {
    "hooks": {
      "pre-commit": "lint-staged --allow-empty",
      "pre-push": "tsc && jest"
    }
  },
  "lint-staged": {
    "{src,__tests__}/**/*.{js,jsx,ts,tsx}": [
      "eslint --fix",
      "prettier --write",
      "git add"
    ],
    "App.tsx": [
      "eslint --fix",
      "prettier --write"
    ]
  },
```

**Comment by QuentinChaumont** [comment]
Same problem..
My setup:
version: "husky": "^4.3.0"
`"husky": {
        "hooks": {
            "pre-commit": "husky/lint-staged.sh",
            "pre-push": "husky/build-staged.sh"
        }
    }`

**Comment by typicode** [comment]
Some users had this behavior when there was another Git hooks manager defined in their `package.json`. So randomly, the other hook manager would replace husky's hooks when `npm install` was run.

Personally, for `v4`, if `pre-commit` stops working, I'd verify that `.git/hooks/pre-commit` is still the one created by husky.

That said, it can be something else.

I'm going to close the issue since it's an old one, but feel free to re-open if you encounter this problem again.
