### ISSUE TITLE
[Feature Request] Migration tool from v4 to v5

### ISSUE THREAD

**Issue by azu** [typicode/husky#812]
Is there a plan to create a migration tool from husky v4 to v5 like `$ husky migrate`?

- https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v5

**Comment by typicode** [comment]
Good question. I've thought about it for some time, only a partial migration tool would be possible.

So my concern is that some users would miss the other important migration steps and that would result in frustration or issues.

While it would be easy to just move commands from `.huskyrc` to `.husky/<file>`, there are few cases where automated migration is complex/not possible
- tools like `commitlint` command needs to be changed from `commitlint -E HUSKY_GIT_PARAMS` to `npx --no-install commitlint --edit $1`
- locally installed commands that were used directly, like `jest` rather than `npm test`, they would need to be run via `npx --no-install jest`
- it's quite important to use `pinst` if the package is published

Also it would need to be done outside of this module, to keep it zero dependency.

That said, maybe if there's enough interest, I'll do it but it'll be just partial for the reason above.

PS: I really like your twitter feed :+1:

**Comment by typicode** [comment]
Forgot to mention, if anyone stumbles on this issue, there's a section in docs for migrating commands from v4 to v5.

**Comment by typicode** [comment]
Found some time, should cover basic needs and help people with many repos :)
https://github.com/typicode/husky-4-to-5 

thanks for the feedback :+1:

**Comment by azu** [comment]
Thanks!

**Comment by azu** [comment]
I [confirmed it works](https://github.com/azu/github-actions-badge/pull/3).

This issue is closed by https://github.com/typicode/husky-4-to-5🎉
