### ISSUE TITLE
v5: a better solution for open-source

### ISSUE THREAD

**Issue by ai** [typicode/husky#868]
Hi. v5 release is so big and I like performance optimization.

But requirements of using `pinst` for open source project (to remove `install` script) is a big blocker for me.

Can we create a simpler workaround? Maybe some `husky-autoinstall` npm package?

**Comment by electerious** [comment]
Thank you for the work you put into Husky 5, but I agree with @ai that—after checking the changelog—Husky v5 isn't the tool of my choice anymore. The best thing about Husky was that it just worked with little configuration. I don't want to add additional scripts or files to my projects. I also liked that I could store the configuration in the package.json along with other configurations for prettier, ava and eslint.

Husky 5 may be lighter and faster, but it lacks what made it so great.

**Comment by lukebrandonfarrell** [comment]
+1 on this @electerious

**Comment by typicode** [comment]
Hi,

Thanks for the feedback. Glad you like the perf improvement (and thanks for PostCSS btw!). 

There are many reasons for this change but I'll try to detail the most important one.

## About postinstall

The `postinstall` change was driven by user's issues with husky 4.

Especially, recent versions of package managers (npm 7 and yarn 2) hide husky 4 output. In other words, users now can't tell if husky 4 install has succeeded or failed and why.

Husky 4 could throw an error and npm/yarn would output the error message but that would fail also the complete install.

This problem is solved by having `postinstall` in `package.json`.

Which leads to pinst.

## About pinst

Since `postinstall` is necessary to show success and error messages, this leads to another problem: there's no hook for dev only postinstall.

I haven't found a better way than disabling `postinstall` when publishing package.

**Comment by ai** [comment]
> I haven't found a better way than disabling

What if we will have `husky-autoinstall`, which will have `husky` as a dependency and `"postinstall": "husky"` in own `package.json`?

Yeap, `husky-autoinstall` will not see `postinstall` errors. But it is an acceptable trade-off for me.

**Comment by kirillgroshkov** [comment]
> Husky 4 could throw an error and npm/yarn would output the error message but that would fail also the complete install.

Why is it bad to throw an error if something went wrong? What could be possible reasons for such errors?

My problem is that I use GUI (SourceTree on Mac) which by default doesn't show the log on commit, so, even if there is something printed there, unless it fails I won't see it. But I'd like to maybe debug and fix issues that Husky reports. If I don't want it to fail on errors - I'd add `skip-hooks` while doing commit.

And I'm asking this, cause I agree with @ai that I preferred the husky4 way of dealing with it, rather than `postinstall`.

**Comment by typicode** [comment]
Some quick update, recently a better way than `postinstall` have been suggested in https://github.com/typicode/husky/issues/884 by @nathansmith 

So, if you're using npm, the recommended way now is just to add `"prepare": "husky install"`. No need for `postinstall` or `pinst` anymore.

Docs have been updated too and adding husky 5 to a project should be easier also with `husky init`.
