### ISSUE TITLE
Want a husky list command

### ISSUE THREAD

**Issue by otakustay** [typicode/husky#894]
We were requiring developers to have husky installed and a `pre-commit` and `pre-push` script configured, in version 4.x we ensure it by parsing `package.json` to see these keys exists in `husky` property

In version 5.x husky hook may installed at a custom directory, this introduces difficulty for automation tools to detect husky script, we'd like to see a `husky ls` command, by running it we can know which hooks are configured

**Comment by typicode** [comment]
Hi @otakustay,

No plans for the moment to include it to the project directly since it's not a common use case.

That said, it can be achieved by running `ls "$(git config core.hooksPath)"` after `npm install`. Alternatively, you could run `grep pattern "$(git config core.hooks)/pre-commit"` to check for some particular content.

It could also be done using JavaScript. For example, checking that `prepare` script in `package.json` contains `husky install`.
