### ISSUE TITLE
chore: fix CI error

### ISSUE THREAD

**Issue by typicode** [typicode/husky#918]
Currently CI fails with error:

```
npm ERR! fsevents not accessible from chokidar
```

Not sure why as it's running fine locally.

**Comment by orditeck** [comment]
Hi,

Your `package-lock.json` is probably out of sync with your `package.json` file. 

Try removing your `package-lock.json` then run `npm i`, commit & push, your CI should now use the synced version.

**Comment by wallw-bits** [comment]
I resolved this for one of our jobs by upgrading `npm` in the ci image (from 6.14.x to latest).

**Comment by niekcandaele** [comment]
Hey, I ran into the same issue (down to the exact same error message) and wandered here via Google.

For me, it was caused because I was using npm 7 locally and npm 6 in CI. We couldn't upgrade to npm 7 in CI because *reasons*.

- Switch to npm 6 locally (or whatever version is used in CI)
- Optional to verify the problem, `npm ci` -> produces the same error as in CI
- `rm package-lock.json`
- `npm i` Regenerate lock file
- `npm ci` works now

**Comment by sebreens** [comment]
@niekcandaele  thanks for the tip. I also have a project were we have npm 6 on the remote and your tip worked.

**Comment by typicode** [comment]
Thanks for the help! It's fixed :+1: 

The `fsevents` error was fixed by adding `--ignore-scipts` to `npm ci`. There were other issues after that but related to husky code and tests.
