### ISSUE TITLE
Why the upgrades?

### ISSUE THREAD

**Issue by mikevercoelen** [typicode/husky#921]
Why was Husky upgraded to v5+ higher and totally changed the structure? It was fine.

Was there a good reason?

It's annoying to keep dependencies up to date and keeping to skip Husky as we don't want the latest, we just want v4.3.8

My suggestion is to make a new package `husky-v4` with the old structure, so we can upgrade all without having to skip Husky.

**Comment by mikevercoelen** [comment]
https://www.npmjs.com/package/husky-v4

**Comment by typicode** [comment]
Hi @mikevercoelen, 

Here's some details as to why https://blog.typicode.com/husky-git-hooks-javascript-config/

Also npm and Yarn have for a long time recommended not to use `postinstall` for anything else than compilation, so husky 5+ is a better citizen in this regard.

What don't you like with this new approach?

Thanks for the fork, it might be a good alternative to people who really want to stay on the previous approach/can't upgrade.

**Comment by mikevercoelen** [comment]
Let me start off by saying I hate to be a buzz kill, and therefore I apologise.

Husky was fine at v4.3.8, v5+ introduces the new `.husky` folder and I don't want this overhead in the root directory of my projects, which already have tons of folders.

It feels to me stuff is getting over engineered, I get it, it's a popular package, you want to maintain it etc. but it was serving it's purpose perfectly fine, no need to drastically change stuff.

**Comment by mcha-dev** [comment]
@typicode thanks for your work 🙏

The previous approach seemed easier but the reasons you gave in the blog post make sense. I think it'll take time but people will get use to it.

**Comment by JounQin** [comment]
You can try https://github.com/toplenboren/simple-git-hooks

**Comment by mcha-dev** [comment]
Probably due to
1. It being a **major** breaking change 🚧
2. License went back to MIT💚

**Comment by appkaiju** [comment]
> What don't you like with this new approach?

I don't want to sound too negative but I really disliked this new version of Husky.

- it introduces a new .husky folder with an additional .gitignore and an additional bash program. more noise and clutter for project maintainers
- now there is a need to run commands to set husky up
- reading the docs I don't understand why I need a prepare that does 'husky install' every time a prepare is supposed to run. now it runs every time a install/add occurs, this feels counter-intuitive and complex
- the problem with the script husky.sh is that I want to get rid of it. it should live inside node_modules/husky. now, a new bash executable lives inside my project. people using other people's projects will think the maintainer wrote it
- if husky.sh is always mandatory, and needs to live inside my project, I should be able to rename it and put it wherever I need/prefer. it would be better to adopt a json configuration approach instead of a bash scripting approach
- the blog post reads like written on the defensive, anxious of criticism. the truth is that project maintainers and regular programmers couldn't care less about package managers recommendations and philosophy, which aren't a standard. people just want to move on with their personal projects. look at the feedback at version 5: https://dev.to/typicode/what-s-new-in-husky-5-32g5 "yeah, husky 5 is pretty #####, I don't get it" / "is much more difficult to understand and config". is their imagination maybe? I spent 6 hours dealing with hooks today instead of actually working. this is so sad

Sorry for the words. It's not bad attitude. As I'm not a native speaker I don't know how to be more subtle. Hope it helps somehow.

**Comment by nemchik** [comment]
I wanted to chime in here. I do agree husky@4 felt simpler. husky@5/6 is actually de-complicating the process in general by just having you manage the hooks in a folder the way `git` uses them (but in `.husky` rather than `.git/hooks`). The simplification of the husky package is a big win for the dev, but again I do agree that husky@4 was easier for users of the package. I have had lots of trouble with husky@5/6 (documented in my recent comment here https://github.com/typicode/husky/issues/864#issuecomment-812131240 ) but I did want to point out that the `.husky/_` folder and the `.husky/_/husky.sh` file inside it (and the `.gitignore` that's somewhere in there) are completely optional. `husky add` or `husky set` place those files there, and place the line in your hook files to source `.husky.sh` in the git hook file (which is interpreted as a shell script by git bash). You can simply remove the entire `.husky` folder, recreate a blank `.husky` folder, and make a `pre-commit` file with a shebang at the top and run whatever you like without the extras from `husky.sh`. The reason it's actually reasonable and good for the `.husky` folder to be where it is: it makes the hooks part of the repo, so all contributors will be on the same page about using the hooks. Why not have `husky.sh` inside `node_modules`? In case someone has not yet installed the `node_modules` but is trying to commit to the repository and their hooks expect to file `husky.sh`.

Anyway I just wanted to clear up a few things about husky@5/6 (p.s. i'm not the dev, just reporting on my experience with using it).

**Comment by typicode** [comment]
Thanks @nemchik for the feedback

> Why not have husky.sh inside node_modules?

Good suggestion. However, husky can't always rely on node_modules to be there. For example, Yarn 2 creates a pnp.js file instead where all modules are.

@appkaiju no worries, I've written an article to explain in details why the new approach (it can be found in the README). I'll write another one for autoinstall (I'll update this issue when it'll be published).

**Comment by nemchik** [comment]
> Thanks @nemchik for the feedback
> 
> > Why not have husky.sh inside node_modules?
> 
> Good suggestion. However, husky can't always rely on node_modules to be there. For example, Yarn 2 creates a pnp.js file instead where all modules are.

Sorry, I should have clarified, me posting that question was in response to @appkaiju asking it in one of his bullet points. I answered the question in the following sentence of my comment.

**Comment by airtonix** [comment]
A lot of whinging in this thread.

If you don't think the current situation with `node_modules` is a problem, then I would say you're living in a bubble. There's some fantastic work happening with yarnpkg and pnp. It looks like husky is preparing for the future, something I can get behind.

As far as I can make out people whinging about having to now manage bash files instead of strings in a JSON file, and that they may see little value in that since it looks like another unnecessary layer on top of normal git hooks?

Perhaps, but you can't commit git hooks to the repo, right?

Personally I feel the right direction is to use layered yaml files for the same reasons people have been asking node/npm to support `package.yml`.

**Comment by appkaiju** [comment]
Nobody was discussing the merits of pnp here, and using offensive expressions like '_whinging_' and '_living in a bubble_' doesn't help neither. I'm leaving, I have no interest in this kind of discussion.

**Comment by mbrevda** [comment]
Having reviewed the blog posts and the changes made, I wonder if there isn't a more moderate approach forward. Here are some thoughts:

- It remains unclear why this package is taking over a `git config`, especially when a perfectly usable solution existed until now.
- While the author maintains that the package managers "recommended not to use postinstall for anything" (albeit no source is given for this), ultimately, the same script will need to be run after every install or change, leading most people to automate this and (blindly) rely on Husky to "do the right thing". At best this would lead  to an illusion of security while putting the onus on the consumer to ensure this script is run
- It's also not clear what benefit there is from including the script in a `husky` directory vs what was previously available

Ultimately the maintainer of a package has the prerogative of designing the package how they see fit. I'd humbly recommend that if ease of use, intuitiveness, or wide spread adoption are goals of this project that the v5/v6 changes be reconsidered.
