### ISSUE TITLE
All husky functionality is lost (no hooks in ./git/hooks anymore?)

### ISSUE THREAD

**Issue by OnkelTem** [typicode/husky#923]
**Troubleshoot**

I have this section in my `package.json`:
```json
  "husky": {
    "hooks": {
      "pre-commit": "npm run lint -s -- --max-warnings=0",
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
    }
  },
```

it worked well before, but now it's being ignored when running `git commit...`

**Context**
I was on husky 5.x when it had stopped working. 

I tried:
```
$ npx husky-init && npm install
```
and it were creating some `./husky` directory but nothing under `.git/hooks`.

I tried also to reinstall husky with:
```
$ npm i -D husky
```
and it didn't change anything.

Finally I removed it completely along with created `.husky` dir, and reinstalled it from scratch and got 6.0.0 version installed.

Then I tried adding some commits but nothing still works.

Any ideas?

**Comment by typicode** [comment]
Hi,

Hooks are now defined in `.husky`. You can run:

```
npx husky-init && npm install
npx husky set .husky/pre-commit "npm run lint -s -- --max-warnings=0"
npx husky set .husky/commitlint "npx --no-install commitlint --edit "$1""
```

I think that npx has currently trouble with `$1`. So you need to edit `.husky/commitlint` and ensure that you have:

```sh
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx --no-install commitlint --edit "$1" # <- $1 needs to be there
```

You can read more about it here:
https://blog.typicode.com/husky-git-hooks-javascript-config/

There's also a CLI to migrate automatically if you have many projects (see docs > migration). But since it's not much you can use the commands above.

If you want to edit hooks, simply edit the files in `.husky/`

**Comment by OnkelTem** [comment]
Oh, thank you, now I see!
That's very serious change and the reasoning is quite reasonable too :P

P.S. I've updated the title a little to make it more specific.

**Comment by OnkelTem** [comment]
@typicode 
There was a little mistype in the third command: 
```
npx husky set .husky/commit-msg "npx --no-install commitlint --edit "$1""

```

**Comment by typicode** [comment]
> There was a little mistype in the third command:

Updated, thanks :)

**Comment by OnkelTem** [comment]
Well, i think it can be closed.
Thanks.
