### ISSUE TITLE
Upgrade to v6 overwrites package.json "prepare" setup

### ISSUE THREAD

**Issue by therealgilles** [typicode/husky#927]
**Context**
I have my .git directory higher up than my package.json file. First I want to say that the documentation on what's different between v4 and v6 is not quite clear to me. I already had a .husky directory, so I think there was nothing for me to change config-wise, but I could not really tell reading the documentation.

Then after I upgraded, my package.json was changed as follows:

```
-               "prepare": "cd ../../.. && husky install <relative-path-to-package-json-dir>/.husky",
+               "prepare": "husky install",
```

which would have been great if the hack wasn't necessary anymore and worked, but it did not. I think, in doubt, nothing should be changed in the package.json unless the user is prompted to apply the change.

**Comment by typicode** [comment]
Thanks for the feedback.

`husky-init` needs to be run only once in a project (that's why `prepare` was reset). If you were already on husky 5, you don't have to make any change or re-run `husky-init` when upgrading to 6.

That said, I'll update `husky-init` to show a message instead or the docs :+1:

**Comment by rafalmaciejewski** [comment]
I'm using prepare task heavily with my team with multiple projects and running this upgrade comes with a risk of breaking them if no manual review will be done or this will be missed. I think that script should prompt the user what to do if there is already prepare task defined in package.json. It would be perfect if it could attach itself into existing one instead of rewriting entire task.

**Comment by typicode** [comment]
Should be fixed with husky-init@6.1.1

**Comment by therealgilles** [comment]
Is there a change log available with commit information?

**Comment by typicode** [comment]
@therealgilles not for `husky-init`. Not sure how to handle it since it's a monorepo and husky-init was upgraded independently. For husky though, the changelog remains in https://github.com/typicode/husky/releases
