### ISSUE TITLE
Support raw git hook names as npm scripts

### ISSUE THREAD

**Issue by julien-f** [typicode/husky#94]
Hi,

I was previously using ghooks which used the raw names for git hooks (`commit-msg` instead of `commitmsg`).

I can understand your preference of removing `-` as it's closer to npm standard scripts but it would make the transition from ghooks easier the raw names were also supported.
Furthermore, I think it's clearer to use the git names because that's what one can find on the Internet.

Plus, I must say that, in my opinion, `commit-msg` is easier to read than `commitmsg`. :)

**Comment by wizardzloy** [comment]
There is another issue with the current hook names. Say you have an npm script called `commit`, then if you define a husky hook "precommit" and run `npm run commit` npm will also automatically execute `precommit` just because of the way npm-scripts work. Is it possible to workaround this situation without renaming the `commit` script?

**Comment by iamstarkov** [comment]
@wizardzloy right now, there is not

**Comment by typicode** [comment]
Closing as next version will use raw names, thanks for the suggestion :)
