### ISSUE TITLE
Yarn 2 doesn't support prepublishOnly

### ISSUE THREAD

**Issue by thislooksfun** [typicode/husky#941]
Since Yarn 2 does not support `prepare` the docs for Yarn 2 say to use `pinst` in `prepublishOnly`. The only issue with that is that [prepublishOnly isn't supported either](https://github.com/yarnpkg/berry/issues/2305#issuecomment-753468942).

**Comment by thislooksfun** [comment]
AFAIK this has not yet been resolved and this should remain open.

**Comment by Sorixelle** [comment]
I'm also running into this issue - haven't come up with a proper solution yet.

**Comment by christophehurpeau** [comment]
According to the documentation (https://yarnpkg.com/advanced/lifecycle-scripts) the "prepublish" script should work, has anyone tried it ?

**Comment by k-j-kim** [comment]
@christophehurpeau, `postinstall` works for me.

`prepublish` does not, since even though the [npm doc](https://docs.npmjs.com/cli/v7/using-npm/scripts#life-cycle-scripts) states that:
> Does not run during npm publish, but does run during npm ci and npm install. See below for more info,

Yarn v2's `prepublish` does not have this behaviour: https://yarnpkg.com/advanced/lifecycle-scripts

However, `postinstall` isn't ideal since it installs for both dev and published environments: https://github.com/yarnpkg/berry/issues/2967

It would be nice if the README can be updated to add an example for both yarn v1 and v2: https://github.com/typicode/husky/blob/main/README.md

**Comment by christophehurpeau** [comment]
thanks for sharing this, but yes the problem is for libraries when postinstall script must be removed before publishing
