### ISSUE TITLE
Question: is `prepare` really a good fit?

### ISSUE THREAD

**Issue by JBBianchi** [typicode/husky#970]
Hello,

I'm new to Husky and I want to start by thanking you for your amazing work.

I saw a discussion about the changes in the new version, people complaining and I'd like to underline that this issue is not about that. Of my personnal experience, not knowing the previous versions, I think this tools is pretty easy to use (and I'm a Windows user, it says it all 🤣)

I just have a question though: why the use of `prepare` ?

I did read the [blog article on the subject](https://blog.typicode.com/husky-git-hooks-autoinstall/) but I must admit that I'm not sure I understand the reasons of the choice.

The first extract from the [npm docs](https://docs.npmjs.com/cli/v7/using-npm/scripts#best-practices) for instance:
```
You should almost never have to explicitly set a preinstall or install script.
If you are doing this, please consider if there is another option. 
The only valid use of install or preinstall scripts is for compilation
```

Doesn't say anything about `postinstall`, only about `preinstall` and `install`.

The other extract from [yarn 2 docs](https://yarnpkg.com/advanced/lifecycle-scripts#a-note-about-postinstall) does give a reason not to use `postinstall` but that still doesn't justify the use of `prepare`. (and I don't want to start another debate but the use of yarn2 itself is [controversial ](https://twitter.com/rich_harris/status/1382397746775220225)😆)

From my understanding, the aim here is to run once (and only once) the install of husky (the .husky dir, .gitignore and .sh file if I'm not mistaken). But `prepare` runs at numerous [stages of the lifecycle](https://docs.npmjs.com/cli/v7/using-npm/scripts#life-cycle-scripts) which leads to unexpected behaviors.

For instance, I build my package in a ./dist/ folder in which I copy the package.json/README.md... before publishing, a bit like angular does with its monorepo projects methodology. This triggers an error `npm ERR! Error: .git can't be found (see https://typicode.github.io/husky/#/?id=custom-directory)` that I cannot really work around without "transforming" my package.json. I cannot use the `cd ..` approach obsviously and using `--ignore-scripts` is not an option because I do use scripts.

To conclude, I think the deprecated `prepublish` (very misleading name) or the disgraced `postinstall` are not so bad and probably more suited than `prepare`. Avoiding their use "just" to comply with yarn is a bit of the opposite way of doing things imo. It's yarn that should adapt to the "specification" not the packages to adapt to yarn.

**Comment by tomsquest** [comment]
Oh, I think I have the same interrogation: by using `prepare` my app cannot be deployed on Google App Engine, as Cloud Build runs `npm ci` with env set to production, and because Husky is a dev dependency.

```
Step #6 - "builder": Running "npm ci --quiet (NODE_ENV=production)"
Step #6 - "builder": 
Step #6 - "builder": > myproject@0.0.0 prepare /workspace
Step #6 - "builder": > husky install
Step #6 - "builder": 
Step #6 - "builder": sh: 1: husky: not found
Step #6 - "builder": npm ERR! code ELIFECYCLE
Step #6 - "builder": npm ERR! syscall spawn
Step #6 - "builder": npm ERR! file sh
Step #6 - "builder": npm ERR! errno ENOENT
Step #6 - "builder": npm ERR! opus-search@0.0.0 prepare: `husky install`
Step #6 - "builder": npm ERR! spawn ENOENT
Step #6 - "builder": npm ERR! 
Step #6 - "builder": npm ERR! Failed at the opus-search@0.0.0 prepare script.
Step #6 - "builder": npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by simonecorsi** [comment]
My doubt about `prepare` is this case:

```Dockerfile
# Dockerfile
RUN npm ci --only=production
```

Am I forced to install husky as a dependency just so the prepare script don't crash? Do I have to add extra checks in the `prepare`?

**Comment by typicode** [comment]
> Doesn't say anything about postinstall, only about preinstall and install.

My understanding is that it applies to `postinstall` as well, since `install` happens after `npm install` just like `postinstall`. It's basically the same kind of hook.
That said, this recommendation applies only to published package.

Running once and only once has led to issues for some people. Also logs are hidden. In practice, it has led to some hard to debug issues.

Ideally, `husky install` should be run in dev only after `npm install`. Unfortunately, there's no `devPostinstall` hooks. The closest thing to that is `prepare`.

`postinstall` can be used if the package is private. If it's published, consuming projects will run `husky install`, which is not wanted.

All in all, you can view husky as a CLI to install and add hooks. It's unopinionated regarding package managers or how it's used. So if for your case, it's better for you to use `postinstall` instead of `prepare`... you can do so :) 

@simonecorsi see https://typicode.github.io/husky/#/?id=disable-husky-in-cidocker once again, there's not one way to handle this. And there's no right or wrong way, depends on your use-case :)

Hope I answered the question :) and thanks for the feedback.

**Comment by simonecorsi** [comment]
@typicode Thank you! I indeed used `is-ci` but had the same problems, I didn't know about `npm set-script prepare ""` I may have missed it on the docs the first time, that's exactly what I've been searching for!
