### ISSUE TITLE
Prepush hook fails on long running tests

### ISSUE THREAD

**Issue by Polyhistor** [typicode/husky#973]
**Context:**
After a few days of necromancy, I realised that Jest test suits that takes more than 100 ms to run will fail the pre-push hook. When I say fail; I don't mean that it just exits the process and doesn't push. I mean that jests will run, the tests will succeed but the actual push is not taking place. 

However, if I breakdown my tests, and just run for example 20 of my tests (less than 100ms) in pre-push hook, the git push will succesfully run after tests succeed! 

In order to recreate this, you'll need one project with so many tests (make sure it takes more than 100ms to run all these tests), and then you'll need to run these tests in a pre-push hook like the below;

```
npm run test  --> this could be just create-react-app test. 

npm_test_exit_code=$?
exit $npm_test_exit_code

```

You can then try it with a smaller number of tests, and you can compare the results. I'm not entirely sure if this is a Husky issue.

Any opinion is much appreciated.

**Comment by typicode** [comment]
Hmm, don't think anything can be done on husky's side or why it fails :/ sorry

**Comment by HagenMorano** [comment]
@Polyhistor 

Ran into a similar issue when trying to run my tests in a pre-push hook. It had indeed nothing to do with husky but with the way ssh times out while being connected to the remote host (in my case gitlab). 

While testing the pre-push with `sleep` it turned out in my case the timeout was at 60 seconds, not 50 seconds as described in the [gitlab troubleshoot](https://docs.gitlab.com/ee/topics/git/troubleshooting_git.html#timeout-during-git-push--git-pull) which was my first guess.

After further investigation, I found a message hidden between the test output:

`Connection to [gitlab host] closed by remote host.`

I was pushing via ssh - so I tried pushing via http which was working as expected. 

### intermediate solution

As I wanted to keep ssh, my intermediate hacky solution was measuring the execution time of the hook. If it exceeds 59 seconds, the hook pushes with the `--no-verify` flag.

```
#!/bin/sh

# if execution time for tests > 59s, pre-push won't respond if using ssh
# and no further action is triggered
# therefore measure execution time and check if it is longer than 60s
# if so, push without triggering hook (--no-verify)
START=`date +%s`
[RUN TEST SCRIPT]
if [ "$?" != 0 ]
then
    echo "One or more tests failing, aborting push"
    exit 1;
fi
END=`date +%s`
DIFF=$(expr $END - $START)
if [ "$DIFF" -gt 59 ]; then
    git push --no-verify
    # if there was no timeout, exit 0 would trigger push again
    exit 0;
fi
exit 0;
```
The downsides of this approach are quite obvious: The timeout may vary, pushing via http always pushes twice and it is far too complicated.

### final solution

In my case, adding a ssh `config` file (`~/.ssh/config` on Linux) on the client like
```
Host [your-host]
  ServerAliveInterval 30
  ServerAliveCountMax 5
```
(validate with `ssh -G [your-host]`) solved the problem.

See also: 
- https://wiki.ubuntuusers.de/SSH/#ssh-config
- https://unix.stackexchange.com/a/3027
